-- Credit for German Localization goes to RunawayCurse on the Curse forums.

if GetLocale() == "deDE" then

	if not LivestockLocalizations then
		LivestockLocalizations = {}
	end

	local L = LivestockLocalizations

	L.LIVESTOCK_FONTSTRING_LIVESTOCKMENU = "Livestock Men\195\188"
	L.LIVESTOCK_FONTSTRING_3DLABEL = "3D Modell"
	L.LIVESTOCK_FONTSTRING_BUTTONSTOGGLETITLE = "Zeige / Verstecke Buttons"
	L.LIVESTOCK_FONTSTRING_MACROBUTTONTITLE = "Livestock Makro Generator"
	L.LIVESTOCK_FONTSTRING_SHOWCRITTERSLABEL = "Haustier"
	L.LIVESTOCK_FONTSTRING_SHOWLANDLABEL = "Land"
	L.LIVESTOCK_FONTSTRING_SHOWFLYINGLABEL = "Flug"
	L.LIVESTOCK_FONTSTRING_SHOWWATERLABEL = "Wasser"
	L.LIVESTOCK_FONTSTRING_SHOWSMARTLABEL = "Smart"
	L.LIVESTOCK_FONTSTRING_MACROBUTTONSTITLE = "Bitte die Dokumentation vor dem Klicken dieser Buttons lesen!"
	L.LIVESTOCK_FONTSTRING_AUTOSUMMONONMOVELABEL = "Automatisch ein Haustier herbeirufen, wenn du dich bewegst."
	L.LIVESTOCK_FONTSTRING_AUTOSUMMONONMOVEFAVELABEL = "Dein bevorzugtes Haustier anstatt eines zuf\195\163lligen herbeirufen."
	L.LIVESTOCK_FONTSTRING_RESTRICTAUTOSUMMONLABEL = "Kein Haustier automatisch herbeirufen, wenn du PVP gekennzeichnet bist."
	L.LIVESTOCK_FONTSTRING_IGNOREPVPRESTRICTIONININSTANCESLABEL = "...es sei denn du bist in einer PVE Instanz."
	L.LIVESTOCK_FONTSTRING_DONOTRAIDSUMMONLABEL = "Kein Haustier automatisch herbeirufen, wenn du in einem Schlachtzug bist."
	L.LIVESTOCK_FONTSTRING_DISMISSPETONMOUNTLABEL = "Das Haustier wegschicken wenn ein Flugreittier bestiegen wird oder in eine Fluggestalt gewechselt wird."
	L.LIVESTOCK_FONTSTRING_CYCLETIMERTOGGLELABEL = "Automatisch dein Tier wechseln nach                             Sekunden."
	L.LIVESTOCK_FONTSTRING_DRUIDTOGGLELABEL = "Ber\195\188cksichtige die Fluggestalt bei Smart Mounting."
	L.LIVESTOCK_FONTSTRING_WORGENTOGGLELABEL = "Ber\195\188cksichtige Wilde Hatz (Worgen) bei Smart Mounting."
	L.LIVESTOCK_FONTSTRING_SAFEFLIGHTLABEL = "Sicherer Flug: In der Luft wird durch einen Aufsteigen-Befehl nicht abgestiegen."
	L.LIVESTOCK_FONTSTRING_AUTODISMISSONSTEALTHLABEL = "Haustier beim Schleichen, Totstellen oder bei Unsichtbarkeit wegschicken."
	L.LIVESTOCK_FONTSTRING_PVPDISMISSLABEL = "Nur wegschicken wenn du PVP gekennzeichnet bist."
	L.LIVESTOCK_FONTSTRING_MOUNTINSTEALTHLABEL = "Schleicheffekte d\195\188rfen beim Aufsteigen abgebrochen werden."
	L.LIVESTOCK_FONTSTRING_USECOMBATFORMSLABEL = "Smart Mounting wechselt im Kampf zum Geisterwolf bzw. in die Reisegestalt."
	L.LIVESTOCK_FONTSTRING_USEMOVINGFORMSLABEL = "Smart Mounting wechselt in den Geisterwolf/die Reisegestalt, w\195\164hrend man sich bewegt (ausserhalb des Kampfes)"
	L.LIVESTOCK_FONTSTRING_SMARTCATFORMLABEL = "Smart Mounting wechselt in Innenr\195\164umen in die Katzengestalt."
	L.LIVESTOCK_FONTSTRING_WATERWALKINGLABEL = "Smart Mounting wirkt %s wenn du Unterwasser bist."
	L.LIVESTOCK_FONTSTRING_CRUSADERSUMMONLABEL = "Ein geeignetes Reittier herbeirufen, nach dem Wirken von Aura des Kreuzfahrers."
	L.LIVESTOCK_FONTSTRING_INDOORHUNTERASPECTSLABEL = "Smart Mounting wirkt Aspekt des Geparden/Rudels in Innenr\195\164umen."
	L.LIVESTOCK_FONTSTRING_MOVINGHUNTERASPECTSLABEL = "Smart Mounting wirkt Aspekt des Geparden/Rudels, w\195\164hrend man sich im Freien bewegt (ausserhalb des Kampfes)."
	L.LIVESTOCK_FONTSTRING_SLOWFALLLABEL = "Smart Mounting wirkt Levitieren / Langsamer Fall beim Fallen (ausserhalb des Kampfes)."

	L.LIVESTOCK_MENU_MORE = "Mehr   >>>"
	L.LIVESTOCK_MENU_SELECTALL = "Alle ausw\195\164hlen"
	L.LIVESTOCK_MENU_SELECTNONE = "Keine ausw\195\164hlen"

	L.LIVESTOCK_ZONE_WINTERGRASP = "Tausendwinter"

	L.LIVESTOCK_TOOLTIP_VERY = "sehr"
	L.LIVESTOCK_TOOLTIP_EXTREMELY = "extrem"
	L.LIVESTOCK_TOOLTIP_FAST = "schnell"
	L.LIVESTOCK_TOOLTIP_LOCATION = "Position"
	L.LIVESTOCK_TOOLTIP_CHANGES = "ver\195\164ndert"
	L.LIVESTOCK_TOOLTIP_NORTHREND = "Nordend"
	L.LIVESTOCK_TOOLTIP_OUTLAND = "Scherbenwelt"

	L.LIVESTOCK_INTERFACE_CRITTERMACROCREATED = LIVESTOCK_HEADER.."Charakterspezifisches Makro zum Herbeirufen eines zuf\195\164lligen Haustiers erstellt!"
	L.LIVESTOCK_INTERFACE_LANDMACROCREATED = LIVESTOCK_HEADER.."Charakterspezifisches Makro zum Herbeirufen eines zuf\195\164lligen Landreittiers erstellt!"
	L.LIVESTOCK_INTERFACE_FLYINGMACROCREATED = LIVESTOCK_HEADER.."Charakterspezifisches Makro zum Herbeirufen eines zuf\195\164lligen Flugreittiers erstellt!"
	L.LIVESTOCK_INTERFACE_SMARTMACROCREATED = LIVESTOCK_HEADER.."Charakterspezifisches Makro zum Herbeirufen eines zuf\195\164lligen Land-/Flugreittiers erstellt!"
	L.LIVESTOCK_INTERFACE_NOCRITTERSCHECKED = LIVESTOCK_HEADER.."Es sind keine Haustiere in deiner Liste.  Bitte tippe "..LIVESTOCK_INTERFACE_SLASHSTRING.." und klicke auf den Haustier Button um eine Auswahl zu treffen."
	L.LIVESTOCK_INTERFACE_NOLANDMOUNTSCHECKED = LIVESTOCK_HEADER.."Es sind keine Landreittiere in deiner Liste.  Bitte tippe "..LIVESTOCK_INTERFACE_SLASHSTRING.." und klicke auf den Landreittier-Button um eine Auswahl zu treffen."
	L.LIVESTOCK_INTERFACE_NOFLYINGMOUNTSCHECKED = LIVESTOCK_HEADER.."Es sind keine Flugreittiere in deiner Liste.  Bitte tippe "..LIVESTOCK_INTERFACE_SLASHSTRING.." und klicke auf den Flugreittier-Button um eine Auswahl zu treffen."
	L.LIVESTOCK_INTERFACE_RESETSAVEDDATA = LIVESTOCK_HEADER.."Gespeicherte Einstellungen wurden gel\195\182scht und die Men\195\188s zur\195\188ckgesetzt.  Bitte kontrolliere die Men\195\188s f\195\188r Haustiere und Reittiere und w\195\164hle die Begleiter ab, die du nicht herbeirufen willst."
	L.LIVESTOCK_INTERFACE_NOFAVEPET = LIVESTOCK_HEADER.."Du hast noch kein bevorzugtes Haustier ausgew\195\163hlt! Ein Rechtsklick auf ein Haustier im Livestock-Men\195\188, macht es zum bevorzugten."
	L.LIVESTOCK_INTERFACE_LISTFAVEPET = LIVESTOCK_HEADER.."Dein bevorzugtes Haustier ist jetzt %s."
	L.LIVESTOCK_INTERFACE_HAVENOTLEARNED = LIVESTOCK_HEADER.."Du hast %s noch nicht erlernt."
	L.LIVESTOCK_INTERFACE_USEITEMLINK = LIVESTOCK_HEADER.."Bitte tippe "..LIVESTOCK_INTERFACE_SLASHSTRING.." [zone/subzone] <Verkn\195\188fung zum Haus- oder Reittier> um dein Reit- oder Haustier f\195\188r die aktuelle Zone bzw. das aktuelle Areal (subzone) festzulegen.  Zum L\195\182schen eines festgelegten Reit- oder Haustiers, tippe "..LIVESTOCK_INTERFACE_SLASHSTRING.." [zone/subzone] [nopet/nomount].  Um dein aktuelles Reit- oder Haustier f\195\188r eine Zone oder ein Areal (subzone) anzuschauen, tippe "..LIVESTOCK_INTERFACE_SLASHSTRING.." [zone/subzone] [whatpet/whatmount]. Alternativ kannst du auch das Optionsmen\195\188 f\195\188r Zonen und Areale aufrufen \195\188ber "..LIVESTOCK_INTERFACE_SLASHSTRING.." prefs."
	L.LIVESTOCK_INTERFACE_CONFIRMZONEADD = LIVESTOCK_HEADER.."Du wirst nun %s herbeirufen als dein %s in der %s %s."
	L.LIVESTOCK_INTERFACE_CONFIRMZONEREMOVE = LIVESTOCK_HEADER.."Du hast jetzt kein %s mehr ausgew\195\164hlt f\195\188r die %s %s."
	L.LIVESTOCK_INTERFACE_DISPLAYZONEPET = LIVESTOCK_HEADER.."Du hast %s als dein %s in der %s %s ausgew\195\164hlt."
	L.LIVESTOCK_INTERFACE_NOZONEPET = LIVESTOCK_HEADER.."Du hast kein %s f\195\188r die %s %s."
	L.LIVESTOCK_INTERFACE_ZONEFRAMEHEADER = "Haus- und Reittiere f\195\188 Zonen und Areale"
	L.LIVESTOCK_INTERFACE_CURRENTZONE = "|cFFEEEE00Aktuelle Zone:|r                      %s"
	L.LIVESTOCK_INTERFACE_CURRENTSUBZONE = "|cFFEEEE00Aktuelles Areal:|r                     %s"
	L.LIVESTOCK_INTERFACE_CURRENTZONEPET = "|cFFEEEE00Haustier f\195\188r aktuelle Zone:|r    %s"
	L.LIVESTOCK_INTERFACE_CURRENTSUBZONEPET = "|cFFEEEE00Haustier f\195\188r aktuelles Areal:|r   %s"
	L.LIVESTOCK_INTERFACE_CURRENTZONEMOUNT = "|cFFEEEE00Reittier f\195\188r aktuelle Zone:|r      %s"
	L.LIVESTOCK_INTERFACE_CURRENTSUBZONEMOUNT = "|cFFEEEE00Reittier f\195\188r aktuelles Areal:|r     %s"
	L.LIVESTOCK_INTERFACE_NOPETSELECTED = "Derzeit kein Haustier ausgew\195\164hlt."
	L.LIVESTOCK_INTERFACE_NOMOUNTSELECTED = "Derzeit kein Reittier ausgew\195\164hlt."
	L.LIVESTOCK_INTERFACE_DRAGERROR = LIVESTOCK_HEADER.."Du kannst nur Reit- und Haustiere in dieses Feld ziehen."
	L.LIVESTOCK_INTERFACE_DRAGBOXEXPL = "Ziehe ein Reit- oder Haustier in dieses Feld, um es als bevorzugtes Reit- oder Haustier\nfestzulegen f\195\188r die aktuelle %s. Mit einem Rechtsklick auf das Feld kannst du das\nhinterlegte Haustier wieder entfernen; mit einem Linksklick das hinterlegte Reittier."
	L.LIVESTOCK_INTERFACE_LAUNCHWEIGHTS = "\195\150ffne Gewichtung f\195\188r zuf\195\164lligen Reittieren"
	L.LIVESTOCK_INTERFACE_USEWEIGHTS = "Verwende Gewichtung f\195\188r zuf\195\164llige Reittiere beim Smart Mounting."

	L.LIVESTOCK_INTERFACE_MAINPANEL = "Livestock"
	L.LIVESTOCK_INTERFACE_PREFSPANEL1 = "Haustiere"
	L.LIVESTOCK_INTERFACE_PREFSPANEL2 = "Fortbewegung / Reittiere"
	L.LIVESTOCK_INTERFACE_PREFSPANEL3 = "Zonen und Areale"
	L.LIVESTOCK_INTERFACE_PREFSPANEL4 = "Gewichtung bei zuf\195\163lligen Reittieren"

end
