-- Credit for the Spanish translation goes to madbit (WoWInterface)

if GetLocale() == "esES" then

	if not LivestockLocalizations then
		LivestockLocalizations = {}
	end

	local L = LivestockLocalizations

	L.LIVESTOCK_FONTSTRING_LIVESTOCKMENU = "Livestock Menu"
	L.LIVESTOCK_FONTSTRING_3DLABEL = "Modelo 3D"
	L.LIVESTOCK_FONTSTRING_BUTTONSTOGGLETITLE = "Mostrar / Ocultar Botones"
	L.LIVESTOCK_FONTSTRING_MACROBUTTONTITLE = "Livestock Macro Generator"
	L.LIVESTOCK_FONTSTRING_SHOWCRITTERSLABEL = "Criaturas"
	L.LIVESTOCK_FONTSTRING_SHOWLANDLABEL = "Terrestres"
	L.LIVESTOCK_FONTSTRING_SHOWFLYINGLABEL = "Voladoras"
	L.LIVESTOCK_FONTSTRING_SHOWWATERLABEL = "Agua"
	L.LIVESTOCK_FONTSTRING_SHOWSMARTLABEL = "Inteligente"
	L.LIVESTOCK_FONTSTRING_MACROBUTTONSTITLE = "Por favor, lea la documentaci\195\179n antes de pulsar estos botontes!"
	L.LIVESTOCK_FONTSTRING_AUTOSUMMONONMOVELABEL = "Invocar una mascota de compa\195\177ia cuando te muevas."
	L.LIVESTOCK_FONTSTRING_AUTOSUMMONONMOVEFAVELABEL = "Invocar tu mascota favorita en lugar de una aleatoria."
	L.LIVESTOCK_FONTSTRING_RESTRICTAUTOSUMMONLABEL = "No invocar mascota si estas maracado con JcJ."
	L.LIVESTOCK_FONTSTRING_IGNOREPVPRESTRICTIONININSTANCESLABEL = "...salvo que est\195\169s en una instancia JcE."
	L.LIVESTOCK_FONTSTRING_DONOTRAIDSUMMONLABEL = "No invocar una mascotas autom\195\161ticamente si est\195\161s en una banda."
	L.LIVESTOCK_FONTSTRING_DISMISSPETONMOUNTLABEL = "Guarda tu mascota cuando saques una montura voladora o uses una forma de vuelo."
	L.LIVESTOCK_FONTSTRING_CYCLETIMERTOGGLELABEL = "Cambiar automaticamente de mascota tras segundos."
	L.LIVESTOCK_FONTSTRING_DRUIDTOGGLELABEL = "Habilitar foma de vuelo con la montura inteligente."
	L.LIVESTOCK_FONTSTRING_WORGENTOGGLELABEL = "Habilitar comportamiento de Galopada salvaje con Montura Inteligente."
	L.LIVESTOCK_FONTSTRING_SAFEFLIGHTLABEL = "Vuelo seguro: usar montar cuando estas en el aire no te desmontar\195\161."
	L.LIVESTOCK_FONTSTRING_AUTODISMISSONSTEALTHLABEL = "Guardar la mascota cuando estes en oculto, fingiendo muerte o lances invisibilidad."
	L.LIVESTOCK_FONTSTRING_PVPDISMISSLABEL = "Solo desinvocar cuando estas marcado para JcJ."
	L.LIVESTOCK_FONTSTRING_MOUNTINSTEALTHLABEL = "Permitir a montar Livestoc que rompa los efectos de ocultaci\195\179n."
	L.LIVESTOCK_FONTSTRING_USECOMBATFORMSLABEL = "Montura Inteligente lanza Lobo Fantasma / Forma de vuelo en combate."
	L.LIVESTOCK_FONTSTRING_USEMOVINGFORMSLABEL = "Montura Inteligente lanza Lobo Fantasma / Forma de vuelo mientras te mueves (fuera de combate)."
	L.LIVESTOCK_FONTSTRING_SMARTCATFORMLABEL = "Montura Inteligente te cambia desde otra forma a Forma de Gato en interiores."
	L.LIVESTOCK_FONTSTRING_WATERWALKINGLABEL = "Montura Inteligente lanza %s cuando est\195\161s bajo el agua."
	L.LIVESTOCK_FONTSTRING_CRUSADERSUMMONLABEL = "Se invoca una montura automaticamente tras lanza Aura de Cruzado."
	L.LIVESTOCK_FONTSTRING_INDOORHUNTERASPECTSLABEL = "Montura Inteligente lanza Aspecto de la Manada/Guepardo en interiores."
	L.LIVESTOCK_FONTSTRING_MOVINGHUNTERASPECTSLABEL = "Montura Inteligente lanza Aspecto de la Manada cuando te mueves (exteriores, fuera de combate)"
	L.LIVESTOCK_FONTSTRING_SLOWFALLLABEL = "Montura Inteligente lanza Levitar / Ca\195\173da lenta cuando caes (fuera de combate)"

	L.LIVESTOCK_MENU_MORE = "M\195\161s   >>>"
	L.LIVESTOCK_MENU_SELECTALL = "Seleccionar todos"
	L.LIVESTOCK_MENU_SELECTNONE = "Seleccionar ninguno"

	L.LIVESTOCK_ZONE_WINTERGRASP = "Conquista del Invierno"

	L.LIVESTOCK_TOOLTIP_VERY = "muy"
	L.LIVESTOCK_TOOLTIP_EXTREMELY = "extremadamente"
	L.LIVESTOCK_TOOLTIP_FAST = "veloz"
	L.LIVESTOCK_TOOLTIP_LOCATION = "zona"
	L.LIVESTOCK_TOOLTIP_CHANGES = "cambia"
	L.LIVESTOCK_TOOLTIP_NORTHREND = "Rasganorte"
	L.LIVESTOCK_TOOLTIP_OUTLAND = "Terrallende"

	L.LIVESTOCK_INTERFACE_CRITTERMACROCREATED = "|cFF4444DDLivestock:|r Macro para invocar criatura aleatoria creada en las macros espec\195\173ficas del jugador!"
	L.LIVESTOCK_INTERFACE_LANDMACROCREATED = "|cFF4444DDLivestock:|r Macro para invocar montura terrestre aleatoria creada en las macros espec\195\173ficas del jugador!"
	L.LIVESTOCK_INTERFACE_FLYINGMACROCREATED = "|cFF4444DDLivestock:|r Macro para invocar montura voladora aleatoria creada en las macros espec\195\173ficas del jugador!"
	L.LIVESTOCK_INTERFACE_SMARTMACROCREATED = "|cFF4444DDLivestock:|r Macro para invocar de forma inteligente monturas terrestres/voladoras creada en las macros espec\195\173ficas del jugador!"
	L.LIVESTOCK_INTERFACE_NOCRITTERSCHECKED = "|cFF4444DDLivestock:|r No hay criaturas en la lista.  Escribe "..LIVESTOCK_INTERFACE_SLASHSTRING.." y haz click en el bot\195\179n de Criaturas para seleccionarlas."
	L.LIVESTOCK_INTERFACE_NOLANDMOUNTSCHECKED = "|cFF4444DDLivestock:|r No hay monturas terrestres en tu lista.  Please type "..LIVESTOCK_INTERFACE_SLASHSTRING.." y haz click en el bot\195\179n de Monturas terrestres para seleccionarlas."
	L.LIVESTOCK_INTERFACE_NOFLYINGMOUNTSCHECKED = "|cFF4444DDLivestock:|r No hay monturas voladoras en tu lista.  Please type "..LIVESTOCK_INTERFACE_SLASHSTRING.." y haz click en el bot\195\179n de Monturas voladoras para seleccionarlas."
	L.LIVESTOCK_INTERFACE_RESETSAVEDDATA = "|cFF4444DDLivestock:|r Se ha borrada la informaci\195\179n guardada y reescrito los men\195\186s.  Ve a los men\195\186s de mascotas y monturas para deseleccionar aquellos que no quieres usar."
	L.LIVESTOCK_INTERFACE_NOFAVEPET = "|cFF4444DDLivestock:|r No has seleccionado una mascota favorita!  Pulsa click derecho con el rat\195\179n en la lista para seleccionarla."
	L.LIVESTOCK_INTERFACE_LISTFAVEPET = "|cFF4444DDLivestock: |r Tu mascota favoria actualmente es %s."
	L.LIVESTOCK_INTERFACE_HAVENOTLEARNED = LIVESTOCK_HEADER.."No has aprendido %s todavía."
	L.LIVESTOCK_INTERFACE_USEITEMLINK = LIVESTOCK_HEADER.."Por favor, use "..LIVESTOCK_INTERFACE_SLASHSTRING.." [zone/subzone] <itemlink> para añadir dos mascota o montura a este area. Para eliminar su mascota o muntura, use /livestock [zone/subzone] [nopet/nomount].  Para ver su mascota o montura actual, use /livestock [zone/subzone] [whatpet/whatmount] o use la interfaz de usuario de Zonas y subzonas de Livestock a través de /livestock prefs"
	L.LIVESTOCK_INTERFACE_CONFIRMZONEADD = LIVESTOCK_HEADER.."Ahora invocar\195\161s %s para tu %s en la %s %s."
	L.LIVESTOCK_INTERFACE_CONFIRMZONEREMOVE = LIVESTOCK_HEADER.."Ya no tienes una %s seleccionada para la %s %s."
	L.LIVESTOCK_INTERFACE_DISPLAYZONEPET = LIVESTOCK_HEADER.."Haz seleccionado %s para tu %s en la %s %s."
	L.LIVESTOCK_INTERFACE_NOZONEPET = LIVESTOCK_HEADER.."No has seleccionado una %s para la %s %s."
	L.LIVESTOCK_INTERFACE_ZONEFRAMEHEADER = "Monturas y Mascotas de Zona y Subzona"
	L.LIVESTOCK_INTERFACE_CURRENTZONE = "|cFFEEEE00Zona actual:|r                   %s"
	L.LIVESTOCK_INTERFACE_CURRENTSUBZONE = "|cFFEEEE00Subzona actual:|r               %s"
	L.LIVESTOCK_INTERFACE_CURRENTZONEPET = "|cFFEEEE00Mascota de zona actual:|r             %s"
	L.LIVESTOCK_INTERFACE_CURRENTSUBZONEPET = "|cFFEEEE00Mascot de subzona actual:|r         %s"
	L.LIVESTOCK_INTERFACE_CURRENTZONEMOUNT = "|cFFEEEE00Montura de zona actual:|r        %s"
	L.LIVESTOCK_INTERFACE_CURRENTSUBZONEMOUNT = "|cFFEEEE00Montura de subzona actual:|r    %s"
	L.LIVESTOCK_INTERFACE_NOPETSELECTED = "Sin mascota seleccionada."
	L.LIVESTOCK_INTERFACE_NOMOUNTSELECTED = "Sin montura seleccionada."
	L.LIVESTOCK_INTERFACE_DRAGERROR = LIVESTOCK_HEADER.."Solo puedes arrastras monturas y mascotas a esta caja."
	L.LIVESTOCK_INTERFACE_DRAGBOXEXPL = "Arrastra una monturas o mascota a esta caja para establecerla como tu compañero deseado\npara la actual %s. Click-derecho sobre la caja para eliminar tu mascota guardada;\nClick izquierdo para eliminar tu montura guardada."
	L.LIVESTOCK_INTERFACE_LAUNCHWEIGHTS = "Abre la interfaz de Prioridades de monturas aleatorias"
	L.LIVESTOCK_INTERFACE_USEWEIGHTS = "Usar prioridades para monturas aleatorias con Montura Inteligente."
	L.LIVESTOCK_INTERFACE_MAINPANEL = "Livestock"
	L.LIVESTOCK_INTERFACE_PREFSPANEL1 = "Mascotas de compa\195\177ia"
	L.LIVESTOCK_INTERFACE_PREFSPANEL2 = "Viaje y monturas"
	L.LIVESTOCK_INTERFACE_PREFSPANEL3 = "Zonas y Subzonas"
	L.LIVESTOCK_INTERFACE_PREFSPANEL4 = "Asignacion de prioridades para Montura Aleatoria"

end
