--[[
************************************************************************
deDE.lua
deDE localization strings for Collectinator
************************************************************************
File date: 2012-09-12T01:10:19Z 
File revision: @file-revision@ 
Project revision: @project-revision@
Project version: 2.0.0beta3
************************************************************************
Currently maintained by:
http://www.wowace.com/addons/collectinator/localization/translators/

Please update http://www.wowace.com/addons/collectinator/localization/deDE/ for any translation
additions or changes.

The translations will be auto-generated by the localization application.
Please make sure you update the ToC file with any translations.
************************************************************************
Please see http://www.wowace.com/addons/collectinator/ for more information.
************************************************************************
These translations are released under the Public Domain.
************************************************************************
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("Collectinator", "deDE", false)

if not L then return end

L["ACQUIRETOOLTIPPOSITION_DESC"] = "Ändert die Position des Tooltips, der Informationen über die Quelle enthält."
L["Acquisition"] = "Quelle"
L["Aeonaxx"] = true
L["Agent Malley"] = true
L["Alani"] = true
L["Aldraan"] = true
L["ALL_FILTERED"] = "Deine Filter verhindern, dass Einträge angezeigt werden. Bitte ändere Deine Filtereinstellungen und versuche es erneut."
L["ALT_CLICK"] = "Alt-Klick zum Hinzufügen/Entfernen dieses Eintrages zu/von Deiner Ignoreliste."
L["Ambersmith Zikk"] = "Bernschmied Zikk"
L["Apothecary Hummel"] = "Apotheker Hummel"
L["Arthur the Faithful"] = "Arthur der Treue"
L["Astrid Langstrump"] = "Astrid Langstrumpf "
L["Audrey Burnhep"] = "Marlene Trichdie"
L["Ayla Shadowstorm"] = "Ayla Schattensturm"
L["Azar Stronghammer"] = "Azar Hammerkraft"
L["Bana Wildmane"] = "Bana Wildmähne"
L["Baradin Fox"] = "Baradinfuchs"
L["Belbi Quikswitch"] = "Belbi Blitzknips"
L["Beldruk Doombrow"] = "Beldruk Schicksalsbraue"
L["Binding"] = "Bindung"
L["Blacksmith Abasi"] = "Schmied Abasi"
L["Blix Fixwidget"] = "Blix Fixtand"
L["Blood Knight Argaron"] = "Blutritter Argaron"
L["BOA_DESC"] = "Accountgebundene Gegenstände in den Scan mit einbeziehen."
L["BOAFilter"] = "Accountgebunden"
L["BOE_DESC"] = "Beim Anlegen gebundene Gegenstände in den Scan mit einbeziehen."
L["BOEFilter"] = "Beim Anlegen gebunden"
L["BOP_DESC"] = "Beim Aufheben gebundene Gegenstände in den Scan mit einbeziehen."
L["BOPFilter"] = "Beim Aufheben gebunden"
L["Bottom Left"] = "Unten Links"
L["Bottom Right"] = "Unten Rechts"
L["Brandur Ironhammer"] = "Brandur Eisenhammer"
L["Breanni"] = true
L["Briarthorn"] = "Wilddornrose"
L["Brother Wilhelm"] = "Bruder Wilhelm"
L["Brunn Flamebeard"] = "Brunn Flammenbart"
L["Challenger Soong"] = "Herausforderer Soong"
L["Challenger Wuli"] = "Herrausforderer Wuli"
L["Champion Bachi"] = true
L["Champion Cyssa Dawnrose"] = "Champion Cyssa Dämmerrose"
L["Chintoka"] = true
L["Chub"] = true
L["Cielstrasza"] = true
L["CLOSE_DESC"] = "Schließt das Collectinator-Fenster"
L["Close GUI"] = "Mit Haus und Reittierfenster schliessen"
L["CLOSEGUI_DESC"] = "Schliesse das Collectinator Fenster wenn das Reit und Haustierfenster geschlossen wird."
L["Collectors Edition"] = true
L["CONTRACTALL_DESC"] = "Minimiert alle Einträge."
L["Coreiel"] = true
L["Corporal Arthur Flew"] = "Korporal Arthur Flew"
L["CTRL_CLICK"] = "Strg-Klick zum Einfügen dieses Eintrages als Link in den Chat."
L["CTRL_SHIFT_CLICK"] = "Strg-Umschalt-Klick zum Hinzufügen des Gegenstandes auf die Karte."
L["Dama Wildmane"] = "Dama Wildmähne"
L["Dame Evniki Kapsalis"] = true
L["Darahir"] = true
L["Darba the Crone"] = "Darba die Greisin"
L["Darkmoon Rabbit"] = "Dunkelmond-Kaninchen"
L["Dealer Rashaad"] = "Händler Rashaad"
L["Demisette Cloyce"] = true
L["Derrick Brindlebeard"] = "Derrick Scheckenbart"
L["Deviate Guardian"] = "Deviatwächter"
L["Deviate Ravager"] = "Deviatverheerer"
L["Dhugru Gorelust"] = "Dhugru Blutgier"
L["DISPLAY_EXCLUSION_DESC"] = "Zeigt Einträge in der Ausschlussliste an."
L["Display Exclusions"] = "Ausschlüsse anzeigen"
L["DISPLAY_OPTIONS_DESC"] = "Einstellungen für die Anzeige ändern."
L["Donni Anthania"] = true
L["Dormus the Camel-Hoarder"] = "Dormus der Kameltreiber"
L["Dorothy"] = "Dorothea"
L["Doru Thunderhorn"] = "Doru Donnerhorn"
L["Drake Dealer Hurlunk"] = "Drachenhändler Hurlunk"
L["Dread Commander Thalanor"] = "Schreckenskommandant Thalanor"
L["Driz Tumblequick"] = "Driz Purzelfix"
L["Durgan Thunderbeak"] = "Durgan Donnerschnabel"
L["Eliza Killian"] = true
L["Evol Fingers"] = "Bosa Blick"
L["EXPANDALL_DESC"] = "Maximiert alle Einträge."
L["Faldoc Stonefaith"] = "Faldoc Steinglaube"
L["Fedryen Swiftspear"] = "Fedryen Flinkspeer"
L["FILTER_CLOSE_DESC"] = "Fensteroberfläche für Filteroptionen schließen."
L["FILTERING_BINDING_DESC"] = "Konfiguration bestimmter Bindungstypen, die in den Scan einbezogen werden sollen."
L["FILTERING_GENERAL_DESC"] = "Konfiguration weiterer, mehr allgemeinerer Filter-Typen."
L["FILTERING_ITEM_DESC"] = "Konfiguration bestimmter Objekt-Typen, die in den Scan einbezogen werden sollen."
L["FILTERING_MISC_DESC"] = "Konfiguration für verschiedene Optionen, die auch in den Darstellungsoptionen vorhanden sind."
L["FILTERING_OBTAIN_DESC"] = "Konfiguration für bestimmte Erarbeitungsmethoden, welche die Einträge benötigen, sollen in den Scan einbezogen werden."
L["FILTERING_REP_DESC"] = "Konfiguration für bestimmte Rufbelohnungs-Einträge, die in den Scan einbezogen werden sollen."
L["FILTER_OPEN_DESC"] = "Öffnet die Filter-Einstellungen."
L["Flik"] = true
L["FONT_SIZE_DESC"] = "Ändert die Schriftgröße."
L["Freka Bloodaxe"] = "Freka Blutaxt"
L["Gaelden Hammersmith"] = "Gaelden Hammerschmied"
L["Galleon"] = true
L["Gina Mudclaw"] = "Gina Lehmkrall"
L["Goram"] = true
L["Gregor MacVince"] = true
L["Grella"] = true
L["Grol'dar"] = true
L["Grunda Bronzewing"] = "Grunda Bronzeflügel"
L["Grunnda Wolfheart"] = "Grunnda Wolfsherz"
L["Gusini"] = true
L["Halpa"] = true
L["Harb Clawhoof"] = "Harb Klauenhuf"
L["Hide Pop-Up"] = "Pop-Up verbergen"
L["HIDEPOPUP_DESC"] = "Verhindert die Anzeige von Pop-Ups, die den Grund weshalb das Scan-Fenster leer ist, mitteilen."
L["Hiren Loresong"] = "Hiren Lehrensang"
L["Irisee"] = true
L["Jadefang"] = "Jadezahn"
L["Jaluu the Generous"] = "Jaluu der Spendable"
L["Jeremiah Payson"] = true
L["Jilanne"] = true
L["Jorek Ironside"] = "Jorek Eisenflanke"
L["Kall Worthaton"] = "Kall Goldkettchen"
L["Katherine the Pure"] = "Katharina die Reine"
L["Katie Hunter"] = "Katie Waidmann"
L["Katie Stokx"] = true
L["Kay Featherfall"] = "Kai Federfall"
L["Kazrali the Witch"] = "Kazrali die Hexe"
L["Kim Horn"] = true
L["Knight Dameron"] = "Ritter Dameron"
L["KNOWN_DESC"] = "Alle bereits bekannten Gegenstände in den Scan mit einbeziehen."
L["Larkin Thunderbrew"] = "Larkin Donnerbräu"
L["Lelanai"] = true
L["Lhara"] = true
L["Lieutenant Karter"] = "Leutnant Karter"
L["Lillehoff"] = true
L["Lil Timmy"] = "Klein Timmy"
L["Location"] = "Ort"
L["Lord Grayson Shadowbreaker"] = "Lord Grayson Schattenbruch"
L["Master Pyreanor"] = "Meister Pyreanor"
L["Maximillian Crowe"] = "Maximillian Raab"
L["Mei Francis"] = true
L["Michelle De Rum"] = true
L["Midsummer Merchant"] = "Sonnenwendhändler"
L["Midsummer Supplier"] = "Sonnenwendversorger"
L["Milli Featherwhistle"] = "Milli Federpfiff"
L["Mirket"] = true
L["Mirla Silverblaze"] = "Mirla Silberstreif"
L["Mob Drop"] = "Mob-Drop"
L["Mycah"] = true
L["Narkk"] = true
L["Nelur Lightsown"] = "Nelur Lichteigen"
L["Noblegarden Merchant"] = "Nobelgartenhändler"
L["Noblegarden Vendor"] = "Nobelgartenverkäufer"
L["NO_DISPLAY"] = "Keine Einträge können angezeigt werden. Falls du diese Mitteilung erhältst, schreibe bitte ein Ticket auf http://www.wowace.com/projects/collectinator/tickets und führe bitte an, welche Filter du angewendet hast, was in deiner Ausschlußliste steht, welche Art von Scan durchgeführt wurde, sowie die Anzahl der bekannten/unbekannten Einträge."
L["NoItemLink"] = "Für diesen Gegenstand gibt es keinen Link oder er war nicht in Deinem Cache."
L["NOTSCANNED"] = "Dieses Sammelobjekt wurde noch nicht gescant. Bitte öffne das Interface und klicke auf Scan. Beachte, dass das Scannen von Reittieren bzw. Fahrzeugen und Haustieren gleichzeitig durchgeführt wird."
L["NOT_YET_SCANNED"] = "Noch nicht gescant!"
L["Obtained From"] = "Quelle"
L["Ogunaro Wolfrunner"] = "Ogunaro Wolfsläufer"
L["Old Whitenose"] = "Der Alte Weißnase"
L["Ordo"] = true
L["\"Plucky\" Johnson"] = "\"Hahnentritt\" Johnson"
L["Pogg"] = true
L["Pol Amberstill"] = "Pol Bernruh"
L["Poseidus"] = true
L["Profile Options"] = "Profil-Einstellungen"
L["Provisioner Nasela"] = "Versorgerin Nasela"
L["Quartermaster Brazie"] = "Rüstmeister Brazie"
L["Raider Bork"] = "Räuber Bork"
L["Randah Songhorn"] = "Randah Liedhorn"
L["Ray'ma"] = true
L["RESET_DESC"] = "Alle Filter auf Standardwerte zurücksetzen."
L["RESET_WINDOW_DESC"] = "Setzt das GUI auf die Standard-Position zurück."
L["Reset Window Position"] = "Fensterposition zurücksetzen"
L["Retired"] = "Entfallen"
L["Richard Kerwin"] = true
L["Riha"] = true
L["Rillie Spindlenut"] = "Rillie Spindelnuss"
L["Rook Hawkfist"] = "Rook Falkenfaust"
L["Rulen Lightsreap"] = "Rulen Lichternter"
L["Rupert Boch"] = "Ruper Boch"
L["Rushi the Fox"] = "Rushi der Fuchs"
L["Sage Lotusbloom"] = "Weise Lotusblüte"
L["Sage Whiteheart"] = "Weiser Weißherz"
L["Sairuk"] = true
L["Samamba"] = true
L["Sandahl"] = true
L["San Redscale"] = "San Rotschuppe"
L["Scan"] = true
L["Scan Button Position"] = "Scan Knopf Position"
L["SCANBUTTONPOSITION_DESC"] = "Erlaubt dir die Position des Scan Knopfes im Reit und Haustierfenster zu wählen."
L["SCAN_COMPANIONS_DESC"] = [=[Scant das aktuell geöffnete Begleiter-Fenster.
SHIFT + Klick, um eine Zeichenkette zu generieren, die auf "Warcraft Pets" hochgeladen werden kann, um deine Sammlung zu aktualisieren.
Alt + SHIFT + Klick, um eine Textablage all deiner Sammelobjekte zu generieren.
Alt + Klick, um alle eingetragenen Standorte auf der Minikarte und auf der Weltkarte zu entfernen.]=]
L["SEARCH_FILTERED"] = "Deine Suche ergab kein ergebnis."
L["Shay Pressler"] = true
L["SHIFT_CLICK"] = "SHIFT + Klick, um den herstellbaren Artikel über diesen Link des Sammelobjektes in den Chat einzufügen."
L["Show Known"] = "Zeige Bekannte"
L["Shylenai"] = true
L["Sixx"] = true
L["Small Font"] = "Kleine Schrift"
L["SOR"] = "Erhaeltlich über Rolle der Auferstehung"
L["SORTING_DESC"] = "Die Art und Weise ändern, in der die dargestellten Sammelobjekte sortiert werden."
L["SPECIFIC_REP_DESC"] = "Fraktion %s einbeziehen."
L["SPELLTOOLTIPPOSITION_DESC"] = "Ändert die Position des Tooltips mit den Sammel-Informationen."
L["Steeg Haskell"] = true
L["Stone Guard Mukar"] = "Steingardist Mutaha"
L["Strahad Farsan"] = true
L["Summoner Calwen"] = "Beschwörer Calwen"
L["Summoner Nolric"] = "Beschwörer Nolric"
L["Sunwalker Atohmo"] = "Sonnenläufer Atohmo"
L["Sunwalker Iopi"] = "Sonnenläufer Iopi"
L["Sunwalker Lonaki"] = "Sonnenläufer Lonaki"
L["Sunwalker Saern"] = "Sonnenläuferin Saern"
L["Tanaika"] = true
L["Tannec Stonebeak"] = "Tannec Steinschnabel"
L["Tan Shin Tiao"] = true
L["TCG"] = "WoW Trading Card Game"
L["Thanthaldis Snowgleam"] = "Thanthaldis Schneeglanz"
L["Thistleheart"] = "Distelherz"
L["Time-Lost Proto Drake"] = "Zeitverlorener Protodrache"
L["Tohfo Skyhoof"] = "Tohfo Himmelshuf"
L["Tooltip (Acquire) Position"] = "Tooltip-Position (erarbeiten)"
L["TOOLTIP_HINT"] = "Verstecke den Hinweis Text"
L["TOOLTIP_HINT_DESC"] = "Versteckt den Hinweis Text am unteren ende des Tooltips"
L["Tooltip Options"] = "Tooltip-Einstellungen"
L["TOOLTIP_OPTIONS_DESC"] = "Hier kann angegeben werden, wie sich die Tooltips verhalten sollen. Der Erarbeitungs-Tooltip listet die verschiedenen Informationen auf, wie ein bestimmtes Sammelobjekt erhalten werden kann, während der Zauber-Tooltip die Informationen zum Sammelobjekt selbst auflistet."
L["Tooltip Position"] = "Hinweistext Position"
L["Tooltip Scale"] = "Tooltip-Skalierung"
L["TOOLTIP_SCALE_DESC"] = "Ändert die Skalierung des Tooltip. Erlaubte Werte zwischen 0.5 und 1.5 (Standardwert: 0.9)."
L["Top Left"] = "Oben Links"
L["Top Right"] = "Oben Rechts"
L["Torallius the Pack Handler"] = "Torallius der Herdentreiber"
L["Trader Narasu"] = "Händler Narasu"
L["Trainer"] = "Lehrer"
L["Trellis Morningsun"] = "Trellis Morgensonne"
L["Tullas"] = true
L["Turtlemaster Odai"] = "Schildkrötenmeisterin Odai"
L["UI_SCALE_DESC"] = "Ändert die Skalierung der UI. Reicht von 0,5 bis 1,5 (1 ist standard)"
L["Uncle Bigpocket"] = "Onkel Dickehose"
L["Unger Statforth"] = "Unger Stattfort"
L["UNKNOWN_DESC"] = "Alle unbekannten Sammelobjekte in den Scan einbeziehen."
L["Ursula Deline"] = true
L["Valadar Starsong"] = "Valadar Sternensang"
L["Varlan Highbough"] = "Varlan Hochblatt"
L["Vasarin Redmorn"] = "Vasarin Morgenröte"
L["Velia Moonbow"] = "Velia Mondbogen"
L["Veron Amberstill"] = "Veron Bernruh"
L["Vindicator Aesom"] = "Verteidiger Aesom"
L["Vitus Darkwalker"] = "Vitus Dunkelwandler"
L["Winaestra"] = true
L["World Drop"] = "Welt-Drop"
L["Xan'tish"] = true
L["Yarlyn Amberstill"] = "Yarlyn Bernruh"
L["Zachariah Post"] = true
L["Zen'Vorka"] = true
L["Zevrost"] = true
L["Zjolnir"] = true
