--[[
************************************************************************
frFR.lua
frFR localization strings for Collectinator
************************************************************************
File date: 2012-09-12T01:10:19Z 
File revision: @file-revision@ 
Project revision: @project-revision@
Project version: 2.0.1
************************************************************************
Currently maintained by:
http://www.wowace.com/addons/collectinator/localization/translators/

Please update http://www.wowace.com/addons/collectinator/localization/frFR/ for any translation
additions or changes.

The translations will be auto-generated by the localization application.

Please make sure you update the ToC file with any translations.
************************************************************************
Please see http://www.wowace.com/addons/collectinator/ for more information.
************************************************************************
These translations are released under the Public Domain.
************************************************************************
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("Collectinator", "frFR", false)

if not L then return end

L["ACQUIRETOOLTIPPOSITION_DESC"] = "Change la position de la bulle d'aide contenant les informations d'acquisition."
L["Acquisition"] = true
L["Aeonaxx"] = true
L["Aldraan"] = true
L["ALL_FILTERED"] = "Vos filtres vous empêchent d'afficher un quelconque résultat. Veuillez changer les réglages de vos filtres et réessayez."
L["ALT_CLICK"] = "Alt-click pour ajouter/retirer cette entrée de votre liste d'objets ignorés"
L["Apothecary Furrows"] = "Apothicaire Furrows"
L["Apothecary Hummel"] = "Apothicaire Hummel"
L["Astrid Langstrump"] = true
L["Ayla Shadowstorm"] = "Ayla Ombretempête"
L["Bana Wildmane"] = "Bana Crin-sauvage"
L["Baradin Fox"] = "Renard de Baradin"
L["Belbi Quikswitch"] = "Belbi Coupecircuit"
L["Binding"] = "Lien"
L["Blacksmith Abasi"] = "Forgeron Abasi"
L["Blix Fixwidget"] = "Blix Réparouage"
L["BOA_DESC"] = "Intègre ou non les entrées qui sont des objets liés au compte dans l'analyse."
L["BOAFilter"] = "Lié au compte"
L["BOE_DESC"] = "Intègre ou non les entrées qui sont des objets liés quand équipés dans l'analyse."
L["BOEFilter"] = "Lié quand équipé"
L["Bogflare Needler"] = "Piqueur Tourbembrase"
L["BOP_DESC"] = "Intègre ou non les entrées qui sont des objets liés quand ramassés dans l'analyse."
L["BOPFilter"] = "Lié quand ramassé"
L["Breanni"] = true
L["Briarthorn"] = "Eglantine"
L["Brunn Flamebeard"] = "Brunn Flammebarbe"
L["Chub"] = "Poupin"
L["Cielstrasza"] = true
L["Clear Exclusion List"] = "Effacer la liste des exclus"
L["CLEAR_EXCLUSION_LIST_DESC"] = "Enlève toutes les entrées de la liste des exclus."
L["Clockwork Assistant"] = "Assistant mécanique"
L["CLOSE_DESC"] = "Ferme la fenêtre de Collectinator."
L["CONTRACTALL_DESC"] = "Minimise toutes les entrées listées ci-dessous."
L["Coreiel"] = true
L["Corporal Arthur Flew"] = "Caporal Arthur Flew"
L["CTRL_CLICK"] = "Ctrl-Clic gauche pour ajouter le lien de cette entrée dans la fenêtre de discussion."
L["CTRL_SHIFT_CLICK"] = "Ctrl-Shift-Clic gauche pour ajouter l'objet sur la carte et la minicarte."
L["Dama Wildmane"] = "Dama Crin-sauvage"
L["Dame Evniki Kapsalis"] = true
L["Darahir"] = true
L["Darkmoon Rabbit"] = "Lapin de Sombrelune"
L["Dealer Rashaad"] = "Camelot Rashaad"
L["Defias Pirate"] = "Pirate défias"
L["Demisette Cloyce"] = true
L["Derrick Brindlebeard"] = "Derrick Piquebarbe"
L["Deviate Guardian"] = "Gardien déviant"
L["Deviate Ravager"] = "Ravageur déviant"
L["Dhugru Gorelust"] = "Dhugru Soif-de-carnage"
L["DISPLAY_EXCLUSION_DESC"] = "Affiche les entrées qui se trouvent dans la liste des exclus."
L["Display Exclusions"] = "Afficher les exclus"
L["DISPLAY_OPTIONS_DESC"] = "Vous permet de personnaliser la façon dont le GUI se comporte."
L["Donni Anthania"] = true
L["Dormus the Camel-Hoarder"] = "Dormus le Collectionneur de dromadaires"
L["Dorothy"] = true
L["Doru Thunderhorn"] = "Doru Corne-tonnerre"
L["Drake Dealer Hurlunk"] = "Camelot de drake Hurlunk"
L["Dread Commander Thalanor"] = "Commandant de l'effroi Thalanor"
L["Driz Tumblequick"] = "Driz Voltevive"
L["Durgan Thunderbeak"] = "Durgan Tonnebec"
L["Eliza Killian"] = true
L["EXCLUDECOUNT_DESC"] = "Intègre ou non les entrées exclues dans le compte total des entrées."
L["EXPANDALL_DESC"] = "Étend toutes les entrées listées ci-dessous."
L["Fedryen Swiftspear"] = "Fedryen Vivelance"
L["FILTER_CLOSE_DESC"] = "Ferme le panneau d'options des filtres"
L["FILTERCOUNT_DESC"] = "Intègre ou non les entrées filtrées dans le compte total des entrées."
L["FILTERING_BINDING_DESC"] = "Configuration des types de liens à intégrer dans l'analyse."
L["FILTERING_GENERAL_DESC"] = "Configuration de plusieurs autres types de filtres généraux."
L["FILTERING_ITEM_DESC"] = "Configuration des types d'objets à intégrer dans l'analyse."
L["FILTERING_MISC_DESC"] = "Configuration des options diverses qui sont également présentes dans les options d'affichage."
L["FILTERING_OBTAIN_DESC"] = "Configuration des méthodes d'obtention à intégrer dans l'analyse."
L["FILTERING_REP_DESC"] = "Configuration des récompenses de réputation à intégrer dans l'analyse."
L["FILTER_OPEN_DESC"] = "Ouvre le panneau d'options des filtres"
L["Flik"] = true
L["FONT_SIZE_DESC"] = "Change la taille des polices."
L["Freka Bloodaxe"] = "Freka Hache-sanglante"
L["Gaelden Hammersmith"] = "Gaelden Forgemartel"
L["Geen"] = true
L["Gregor MacVince"] = true
L["Grella"] = true
L["Grol'dar"] = true
L["Grunda Bronzewing"] = "Grunda Aile-de-Bronze"
L["Grunnda Wolfheart"] = "Grunnda Coeur-de-loup"
L["Gundrak Raptor"] = "Raptor de Gundrak"
L["Halpa"] = true
L["Harb Clawhoof"] = "Harb Sabot-griffu"
L["Hide Pop-Up"] = "Cacher pop-ups"
L["HIDEPOPUP_DESC"] = "Empêche l'affichage des pop-ups indiquant pourquoi la fenêtre d'analyse est vide. Ces pop-ups seront toujours affichées la tout première fois après qu'une nouvelle version de l'addon a été installée."
L["Hiren Loresong"] = "Hiren Chanterite"
L["Include Excluded"] = "Intégrer les exclus"
L["Include Filtered"] = "Intégrer les filtrés"
L["Irisee"] = true
L["Jadefang"] = "Jadecroc"
L["Jepetto Joybuzz"] = "Jepetto Mizanjoie"
L["Jeremiah Payson"] = true
L["Jilanne"] = true
L["Kall Worthaton"] = "Kall Vauthaton"
L["Katie Hunter"] = true
L["Knight Dameron"] = "Chevalier Dameron"
L["KNOWN_DESC"] = "Intègre tous les objets de collection connus dans l'analyse."
L["Larkin Thunderbrew"] = "Larkin Tonnebière"
L["Lelanai"] = true
L["Lhara"] = true
L["Lieutenant Karter"] = true
L["Lillehoff"] = true
L["Lil Timmy"] = "Jeune Timmy"
L["Location"] = "Emplacement"
L["Main Filter Options"] = "Options principales des filtres"
L["MAINFILTER_OPTIONS_DESC"] = "Vous permet de spécifier comment les différents filtres sont gérés."
L["Main Options"] = "Options principales"
L["MAIN_OPTIONS_DESC"] = "Options principales de configuration"
L["Maximillian Crowe"] = true
L["Mei Francis"] = true
L["Michelle De Rum"] = true
L["Midsummer Merchant"] = "Marchand du solstice"
L["Midsummer Supplier"] = "Fournisseur du solstice"
L["Milli Featherwhistle"] = "Milli Siffleplume"
L["Mirket"] = true
L["Miscellaneous"] = "Divers"
L["Mob Drop"] = "Butin de monstre"
L["Mycah"] = true
L["Narkk"] = true
L["Noblegarden Merchant"] = "Marchand du Jardin des nobles"
L["Noblegarden Vendor"] = "Vendeur du Jardin des nobles"
L["NO_DISPLAY"] = "Aucune entrée à afficher. Si vous obtenez ce message, veuillez envoyer un ticket à l'adresse http://www.wowace.com/projects/collectinator/tickets en indiquant les filtres que vous avez activés, le contenu de votre liste des exclus, le type d'analyse effectuée et le nombre d'entrées connues/inconnues."
L["NoItemLink"] = "Cet objet n'a pas de lien ou n'est pas encore de votre cache."
L["NOTSCANNED"] = "Les familiers/montures n'ont pas encore été scannées. SVP ouvrez l'interface et appuyez sur Analyser. L'analyse des familiers/montures sont faites en même temps."
L["NOT_YET_SCANNED"] = "Pas encore analysé !"
L["Noxious Whelp"] = "Dragonnet nocif"
L["Obtained From"] = "Moyen(s) d'obtention"
L["Ogunaro Wolfrunner"] = "Ogunaro Mène-loup"
L["\"Plucky\" Johnson"] = "Johnson « le Brave »"
L["Pogg"] = true
L["Pol Amberstill"] = "Pol Distillambre"
L["Poseidus"] = "Poséidus"
L["Profile Options"] = "Options du profil"
L["Provisioner Nasela"] = "Approvisionneur Nasela"
L["Quartermaster Brazie"] = "Intendant Brazie"
L["Raider Bork"] = "Ecumeur Bork"
L["Ray'ma"] = true
L["RESET_DESC"] = "Réinit.des filtres."
L["RESET_WINDOW_DESC"] = "Place l'UI à sa position d'origine"
L["Reset Window Position"] = "Réinit. la position de la fenêtre"
L["Retired"] = "Enlevés"
L["Richard Kerwin"] = true
L["Rillie Spindlenut"] = "Rillie Fuseboulon"
L["Rook Hawkfist"] = "Freux Poing-faucon"
L["Rupert Boch"] = true
L["Sairuk"] = true
L["Samamba"] = true
L["Sandahl"] = true
L["Scalding Whelp"] = "Dragonnet flamboyant"
L["Scan"] = "Analyser"
L["SCAN_COMPANIONS_DESC"] = [=[Analyse la fenêtre actuellement ouverte.
Shift-clic gauche pour générer un string qui peut être envoyé à Warcraft Pets pour mettre à jour votre collection.
Alt-Shift-clic gauche pour générer un text dump des objets de collection que vous possédez.
Alt-clic gauche pour enlever tous les points de navigation de la minicarte et de la carte du monde.]=]
L["Searing Whelp"] = "Dragonnet incendiaire"
L["SHIFT_CLICK"] = "Shift-Clic pour ajouter l'article fabriqué par le lien d'objet de collection vers votre fenêtre de discussion."
L["Shylenai"] = true
L["Sixx"] = true
L["SORTING_DESC"] = "Change la façon dont les objets de collection sont triés."
L["SPECIFIC_REP_DESC"] = "Intègre ou non la faction %s."
L["SPELLTOOLTIPPOSITION_DESC"] = "Change la position de la bulle d'aide affichant les informations sur les objets collectionnables."
L["Stone Guard Mukar"] = "Garde de pierre Mukar"
L["Strahad Farsan"] = true
L["Tanaika"] = true
L["TCG"] = "WoW Trading Card Game"
L["Thanthaldis Snowgleam"] = "Thanthaldis Luireneige"
L["Thistleheart"] = "Coeurdechardon"
L["Time-Lost Proto Drake"] = "Proto-drake perdu dans le temps"
L["Tohfo Skyhoof"] = "Tohfo Sabot-du-ciel"
L["Tooltip (Acquire) Position"] = "Position de la bulle d'acquisition"
L["Tooltip Options"] = "Options de la bulle d'aide"
L["TOOLTIP_OPTIONS_DESC"] = "Vous permet de définit la façon dont les bulles d'aide se comportent. La bulle d'aide d'acquisition affiche les différentes informations sur la façon d'obtenir l'objet de collection, tandis que la bulle d'aide du sort affiche les informations concernant l'objet de collection en lui-même."
L["Tooltip Scale"] = "Échelle de la bulle d'aide"
L["TOOLTIP_SCALE_DESC"] = "Change l'échelle de la bulle d'aide. De 0.5 à 1.5 (1 par défaut)"
L["Torallius the Pack Handler"] = "Torallius le Pâtre"
L["Trader Narasu"] = "Marchand Nasaru"
L["Trellis Morningsun"] = "Trellis Solmatin"
L["UI_SCALE_DESC"] = "Change l'échelle de l'interface. Réglable de 0.5 à 1.5 (1 par défaut)"
L["Unger Statforth"] = true
L["UNKNOWN_DESC"] = "Inclure tous les objets collectionnables inconnus dans l'analyse."
L["Ursula Deline"] = true
L["Valadar Starsong"] = "Valadar Chantétoile"
L["Varlan Highbough"] = "Varlan Hautebranche"
L["Vasarin Redmorn"] = "Vasarin Rougematin"
L["Veron Amberstill"] = "Veron Distillambre"
L["View Exclusion List"] = "Voir liste des exclus"
L["VIEW_EXCLUSION_LIST_DESC"] = "Affiche une liste de toutes les entrées contenues dans la liste des exclus."
L["Winaestra"] = true
L["World Drop"] = "Butin mondial"
L["Xan'tish"] = true
L["Yarlyn Amberstill"] = "Yarlyn Distillambre"
L["Zachariah Post"] = true
L["Zen'Vorka"] = true
L["Zevrost"] = true
L["Zjolnir"] = true
