--[[
************************************************************************
ptBR.lua
ptBR localization strings for Collectinator
************************************************************************
File date: 2012-09-12T01:10:19Z 
File revision: @file-revision@ 
Project revision: @project-revision@
Project version: 2.0.2
************************************************************************
Currently maintained by:
http://www.wowace.com/addons/collectinator/localization/translators/

Please update http://www.wowace.com/addons/collectinator/localization/ptBR/ for any translation
additions or changes.

The translations will be auto-generated by the localization application.

Please make sure you update the ToC file with any translations.
************************************************************************
Please see http://www.wowace.com/addons/collectinator/ for more information.
************************************************************************
These translations are released under the Public Domain.
************************************************************************
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("Collectinator", "ptBR", false)

if not L then return end

L["Aldraan"] = true -- Needs review
L["Bana Wildmane"] = "Bana Juba Agreste" -- Needs review
L["Belbi Quikswitch"] = "Bebel Trocarrápida" -- Needs review
L["Blix Fixwidget"] = "Blix Consertatreco" -- Needs review
L["Bogflare Needler"] = "Agulheiro Brejolume" -- Needs review
L["Breanni"] = true -- Needs review
L["Brunn Flamebeard"] = "Bruno Barbachama" -- Needs review
L["Darahir"] = true -- Needs review
L["Dealer Rashaad"] = "Mercador Rashaad" -- Needs review
L["Defias Pirate"] = "Pirata Défias" -- Needs review
L["Derrick Brindlebeard"] = "Derico Barbalistra" -- Needs review
L["Deviate Guardian"] = "Guardião Anormal" -- Needs review
L["Deviate Ravager"] = "Assolador Anormal" -- Needs review
L["Donni Anthania"] = "Cristiana Justa" -- Needs review
L["Doru Thunderhorn"] = "Doru Chifre Troante" -- Needs review
