local _,L = ...
if GetLocale()=="zhTW" then

-- New or changed strings in 3.1.8:
	L["Without Any 25s"] = "未滿25級"
	L["2+ Pets"] = "已收集2/3"
	L["3+ Pets"] = "已收集3/3"

-- New or changed strings in 3.1.4:
	L["Only Level 25s"] = "僅25級"
	L["Level 25"] = "25級"
	L["Reset filters on login"] = "登錄時重置過濾器"
	L["Reset all pet browser filters (except sort order) when logging in."] = "登錄時重置寵物瀏覽頁所有過濾設定(排序除外)."
	L["Load Filters"] = "讀取過濾器設定"
	L["Save Filters"] = "保存過濾器設定"
	L["Do you want to overwrite the existing saved filters?"] = "確定更新過濾器設定?"

-- New or changed strings in 3.1.3:
	L["This team did not automatically load because you've already auto-loaded a team from where you're standing."] = "該組合沒有加載.因為另一個組合已經被載入."
	L["This pet is currently slotted."] = "寵物已在寵物欄位"

-- New or changed strings in 3.1.2:
	L["Undo"] = "撤銷"
	L["Revert to the last saved notes. Changes are saved when leaving these notes."] = "恢復至上次保存的內容."
	L["Delete Notes"] = "刪除注釋"
	L["Disable ESC for notes"] = "禁用Esc鍵關閉注釋"
	L["Prevent the notes card from being dismissed with the Escape key."] = "防止誤操作Esc鍵致使注釋頁關閉."
	L["Close everything with ESC"] = "用Esc鍵執行所有關閉動作"
	L["Close all Escape-enabled Rematch windows at once with the Escape key instead of one at a time."] = "用Esc鍵一次性關閉所有已開啟的窗口."

-- New or changed strings in 3.1.1:
	L["Show notes in battle"] = "戰鬥中顯示注釋"
	L["If the loaded team has notes, display and lock the notes when you enter a pet battle."] = "如果加載的組合添加了注釋,戰寵對戰時，顯示并鎖定該注釋."
	L["Hide rarity borders"] = "隱藏稀有邊框"
	L["Hide the colored borders to indicate rarity around current pets and pets on the team cards."] = "隱藏組合中稀有戰寵的顏色邊框."
	L["Discard loaded team on changes"] = "忽略組合變化"
	L["This option changes the normal behavior of Rematch and its interaction with targets. Specifically, any time you change pets or abilities, it will disregard what you have loaded in the past and always offer to load/show teams. Also, it will be very difficult to save changes to teams by targeting. The Reload button will also be disabled. \124cffff2222WARNING!\124cffffd200 This option is not recommended!"] = "忽略組合中戰寵/技能設定變化,按既定目標加載組合.\n\124cffff2222警告!\124cffffd200 不建議開啟此選項!"

-- New or changed strings in 3.1.0:
	L["List real names"] = "列表顯示戰寵默認名稱"
	L["Even if a pet has been renamed, list each pet by its real name."] = "列表中顯示戰寵的默認名稱(忽略自定義名稱)."
	L["Fill the leveling queue with one of each species that can level from the filtered pet browser, and for which you don't have a level 25 already."] = "Fill the leveling queue with one of each species that can level from the filtered pet browser, and for which you don't have a level 25 already."
	L["Fill Queue More"] = "批量加入升級隊列"
	L["Fill the leveling queue with one of each species that can level from the filtered pet browser, regardless whether you have any at level 25 already."] = "從戰寵類型過濾器選擇可以升級的戰寵,批量加入至升級隊列."
	L["\124cffccccccThere are no notes for this team.\n\nYou can add a note by right-clicking the team in the team tab and choosing Set Notes."] = "\124cffcccccc這個組合沒有注釋.\n\n右鍵單擊該組合,可以添加注釋."
	L["Notes for this team:"] = "注釋:"
	L["Set Notes"] = "添加注釋"
	L["Save these notes?"] = "保存注釋?"

-- New or changed strings in 3.0.13:
	L["Reload"] = "刷新"
	L[" \124cffffd200Note:\124r Enabling this option disables the 'Reload' button."] = " \124cffffd200注意:\124r 啟用此選項將禁用‘刷新’按鍵."

-- New or changed strings in 3.0.11:
	L["Even options"] = "隱藏選項介面提示"
	L["Also hide tooltips that appear here in the options panel. This is not recommended if you're new to the addon."] = "隱藏選項面板中的提示. \n如果你對本插件不熟悉,不建議啟用該選項."
	L["Larger list text"] = "大型字體"
	L["Make the text in the scrollable lists (pets, teams and options) a little bigger."] = "寵物/組合列表及選項介面使用大型字體."
	L["Reverse dialog direction"] = "Rematch 窗口右側顯示對話框"
	L["When displaying a popup dialog adjacent to the Rematch window, make them appear on the side towards the edge of the screen instead of towards the center."] = "彈出式對話框顯示在 Rematch 窗口右側,而不是在 Rematch 窗口中間."
	L["In a Team"] = "已在組合"
	L["Not In a Team"] = "不在組合"

-- New or changed strings in 3.0.10:
	L["Stay after loading"] = "Rematch 窗口駐留"
	L["Keep the Rematch window on screen after loading a team when the window was shown via 'Auto show on target'."] = "'自動顯示 Rematch 窗口'選項啟用時,加載組合后,顯示 Rematch 窗口."
	L["Show after loading"] = "Rematch 窗口顯示"
	L["When a team is automatically loaded, show the Rematch window if it's not already shown."] = "組合自動加載后,顯示 Rematch 窗口,如果該窗口尚未顯示."

-- New or changed strings in 3.0.9:
	L["Show dialogs at side"] = "Rematch 窗口左側顯示對話框"
	L["Instead of making popup dialogs appear in the middle of the expanded Rematch window, make them appear to the side."] = "彈出式對話框顯示在 Rematch 窗口左側,而不是在 Rematch 窗口中間."

-- New or changed strings in 3.0.1 to 3.0.7:
	L["When targeting something with a saved team not already loaded, show the Rematch window."] = "目標已保存戰寵組合,但未能加載時,顯示 Rematch 窗口."
	L["Auto load"] = "自動加載"
	L["When your mouseover or target has a saved team not already loaded, load the team immediately."] = "鼠標懸停或點擊目標時,自動加載戰寵組合."
	L["On target only"] = "目標加載"
	L["Auto load will only happen when you target, not mouseover. \124cffff2222WARNING!\124cffffd200 This option is not recommended! It is often too late to load pets when a battle starts if you target with right-click!"] = "只有點擊目標時才自動加載組合.\n\124cffff2222警告!\124cffffd200 不建議開啟此選項! 如果你使用右鍵與目標互動，該選項有可能造成加載延遲!"
	L["Always show or load"] = "始終顯示/加載"
	L["Continue to offer to load (or auto load) teams if any pets or abilities are changed in the loaded team."] = "當組合中的戰寵或技能改變時,也繼續加載該組合."
	L["Prevent the Rematch window from being dragged unless Shift is held."] = "鎖定 Rematch 窗口位置.\nSHIFT+左鍵點擊移動."
	L["Don't warn about missing pets"] = "隱藏丟失寵物警告"
	L["Don't display a popup when a team loads and a pet within the team can't be found."] = "當組合中的寵物丟失時,隱藏丟失寵物警告."
	L["Jump to key"] = "按鍵跳轉"
	L["While the mouse is over the team list or pet browser, hitting a key will jump to the next team or pet that begins with that letter."] = "鼠標懸停在戰寵組合列表或戰寵瀏覽頁時,根據按鍵,跳轉到相應字母/數字的戰寵組合或戰寵.\n（例如:在鼠標懸停在戰寵瀏覽頁,按X鍵,會自動跳轉到“XT小小拆解者”.只支持首字爲字母/數字的組合名/戰寵名,不支持中文）."
	L["Pets are missing!"] = "寵物丟失!"
	L["Press CTRL+C to copy this team to the clipboard."] = "CTRL+ C 複製組合."
	L["Press CTRL+V to paste a team from the clipboard."] = "CTRL+V 粘貼組合."

-- common.lua
	L["Toggle Window"] = "切換窗口"
	L["Toggle Auto Load"] = "切換自動加載"
	L["Toggle Pets"] = "切換戰寵"
	L["Toggle Teams"] = "切換組合"
	L["Toggles the Rematch window to manage battle pets and teams."] = "切換戰寵/組合窗口."

-- main.lua
	L["Import"] = "導入"
	L["Options"] = "選項"
	L["Teams"] = "組合"
	L["\124cffff8800You're in combat. Blizzard has restrictions on what we can do with pets during combat. Try again when you're out of combat. Sorry!"] = "\124cffff8800戰鬥中無法操作,請脫離戰鬥后重試!"
	L["\124cffffff00Rematch Auto Load is now"] = "\124cffffff00Rematch 自動加載"
	L["\124cff00ff00Enabled"] = "\124cff00ff00啟用"
	L["\124cffff0000Disabled"] = "\124cffff0000禁用"
	L["Current Battle Pets"] = "當前戰寵"
	L["\124cffffd200PetBattleTeams is not enabled. Try again when the addon is enabled."] = "\124cffffd200Pet Battle Teams 未啟用."

-- floatingpetcard.lua
	L["Damage Taken"] = "承受\n傷害"
	L["from"] = "Vs."
	L["abilities"] = " "
	L["No breeds known :("] = "未知品種"
	L["\124cffddddddPossible level 25 \124cff0070ddRares"] = "\124cffdddddd可能是25級\124cff0070dd的稀有戰寵"

-- leveling.lua
	L["Queued:"] = "升級隊列:"
	L["Leveling:"] = "升級寵:"
	L["Sort:"] = "排序:"
	L["This is the leveling slot.\n\nDrag a level 1-24 pet here to set it as the current leveling pet.\n\nWhen a team is saved with the current leveling pet, that pet's place on the team is reserved for future leveling pets.\n\nThis slot can contain as many leveling pets as you want. When a pet reaches 25 the topmost pet in the queue becomes your new leveling pet."] = "戰寵升級欄.\n\n放入待升級的戰寵,會按順序依次升級."
	L["\124TInterface\\Buttons\\UI-GroupLoot-Pass-Up:16\124t This pet can't level"] = "\124TInterface\\Buttons\\UI-GroupLoot-Pass-Up:16\124t  該戰寵不能升級"
	L["\124TInterface\\Buttons\\UI-GroupLoot-Pass-Up:16\124t The queue is sorted"] = "\124TInterface\\Buttons\\UI-GroupLoot-Pass-Up:16\124t 升級隊列排序完成"
	L["This pet is already in the queue.\nPets can't move while the\nqueue is sorted"] = "該戰寵已在升級隊列中.\n升級隊列排序時,不能移動戰寵."
	L["\124TInterface\\DialogFrame\\UI-Dialog-Icon-AlertNew:16\124t The queue is sorted"] = "\124TInterface\\DialogFrame\\UI-Dialog-Icon-AlertNew:16\124t 升級隊列排序完成"
	L["This pet will be added to the\nend of the unsorted queue."] = "該戰寵將添加至未排序的升級隊列末端."
	L["\124cffff8800The current leveling pet is in battle and can't be swapped."] = "\124cffff8800當前升級寵在戰鬥中,無法交換."
	L["Next leveling pet:"] = "下一個升級寵："

-- rmf.lua
	L["Empty Slot"] = "空欄"
	L["Choose a name."] = "選擇一個名稱."
	L["Restore original name"] = "恢復原名"
	L["Release this pet?"] = "釋放這隻寵物?"
	L["Once released, this pet is gone forever!"] = "釋放后將無法找回!"
	L["Cage this pet?"] = "放入籠子?"
	L["Current Zone"] = "當前區域"
	L["Strong Vs"] = "克制"
	L["Tough Vs"] = "減傷"
	L["Reset All"] = "重置分類"
	L["Use Type Bar"] = "啓用戰寵類型過濾圖示"
	L["Leveling"] = "已在升級隊列"
	L["Not Leveling"] = "未在升級隊列"
	L["Tradable"] = "可交易"
	L["Not Tradable"] = "不可交易"
	L["Can Battle"] = "可對戰"
	L["Can't Battle"] = "不可對戰"
	L["1 Pet"] = "已收集1/3"
	L["2 Pets"] = "已收集2/3"
	L["3 Pets"] = "已收集3/3"
	L["Start Leveling"] = "開始升級"
	L["Add to Leveling Queue"] = "添加到升級隊列"
	L["Stop Leveling"] = "停止升級"
	L["Put Leveling Pet Here"] = "放置升級寵"
	L["Move to Top"] = "頂端"
	L["Move Up"] = "上移"
	L["Move Down"] = "下移"
	L["Move to End"] = "末端"
	L["Fill Queue"] = "加入升級隊列"
	L["This will add %d pets to the leveling queue.\n%s\nAre you sure you want to fill the leveling queue?"] = "%d 戰寵將添加至升級隊列中.\n%s\n\n\n確認將所選戰寵加入到升級隊列嗎?\n"
	L["\nYou can reduce the number of pets by filtering them in Rematch's pet browser\n\nFor instance: search for \"21-24\" and filter Rare only to fill the queue with rares between level 21 and 24.\n"] = "\n你可以通過戰寵瀏覽頁的搜索/過濾等方式來篩選寵物.\n例如: 搜索 \"21-24\" 可以將加入升級隊列的戰寵等級設定在21-24之間."
	L["\nAll species with a pet that can level already have a pet in the queue.\n"] = "\n已經有相同的升級寵在升級隊列中.\n"
	L["Empty Queue"] = "清空升級隊列"
	L["Are you sure you want to remove all pets from the leveling queue?"] = "確認將所有戰寵從升級隊列中移除?"
	L["Queue"] = "升級隊列"
	L["Sort Order:"] = "排序方式:"
	L["Ascending"] = "升序"
	L["Sort:\124cffffd200Ascending"] = "排序方式:\124cffffd200升序"
	L["Sort the queue from\nlevel 1 to level 25."] = "按1-25級排序."
	L["Descending"] = "降序"
	L["Sort:\124cffffd200Descending"] = "排序方式:\124cffffd200降序"
	L["Sort the queue from\nlevel 25 to level 1."] = "按25-1級排序."
	L["Median"] = "中間值"
	L["Sort:\124cffffd200Median"] = "排序方式:\124cffffd200中間"
	L["Sort the queue for\nlevels closest to 10.5."] = "接近11級的戰寵會排在隊列的前端."
	L["Auto Rotate"] = "自動循環"
	L["After the leveling pet gains xp:\n\n\124cffffd200Ascending\124cffe6e6e6 and \124cffffd200Median\124cffe6e6e6 sorts will swap\nto the top-most pet in the queue.\n\n\124cffffd200Unsorted\124cffe6e6e6 and \124cffffd200Descending\124cffe6e6e6 sort will\nswap to the next pet in the queue."] = "當戰寵獲得經驗之後:\n\n\124cffffd200升序\124cffe6e6e6 及 \124cffffd200中間\124cffe6e6e6 方式下,該戰寵將在升級隊列頂端.\n\n\124cffffd200未排序\124cffe6e6e6 及 \124cffffd200降序\124cffe6e6e6 方式下,該戰寵將在升級隊列末端."
	L["Fill the leveling queue with one of\neach species that can level from\nthe filtered pet browser."] = "你可以通過戰寵瀏覽頁的搜索/過濾等方式來篩選寵物,\n并將它們加入到升級隊列中."
	L["Remove all leveling pets\nfrom the queue."] = "清空升級隊列中所有戰寵."
	L["Edit"] = "編輯"
	L["Delete this team?"] = "刪除該組合?"
	L["Load"] = "加載"
	L["Load Team"] = "加載組合"
	L["You can double-click\na team to load also."] = "雙擊加載該組合."
	L["Rename"] = "重新命名"
	L["Move To"] = "移至"
	L["Send"] = "發送"
	L["Export"] = "導出"
	L["Save To"] = "保存至"

-- options.lua
	L["Targeting Options"] = "目標 選項"
	L["Auto show on target"] = "自動顯示 Rematch 窗口"
	L["Window Options"] = "介面 選項"
	L["Larger window"] = "大型窗口"
	L["Make the Rematch window larger for easier viewing."] = "使用 Rematch 大窗口樣式."
	L["Reverse pullout"] = "工具欄置頂"
	L["When the Pets or Teams tab is opened, expand the window down the screen instead of up."] = "工具欄置于寵物/組合列表的頂端."
	L["Lock window position"] = "鎖定窗口位置"
	L["Lock window height"] = "鎖定窗口高度"
	L["Prevent the window's height from being resized with the resize grip along the bottom of the expanded window."] = "鎖定 Rematch 窗口高度."
	L["Disable ESC for window"] = "禁用ESC鍵關閉 Rematch 窗口"
	L["Prevent the Rematch window from being dismissed with the Escape key."] = "禁用ESC鍵關閉 Rematch 窗口."
	L["Disable ESC for drawer"] = "禁用ESC鍵關閉寵物/組合列表"
	L["Prevent the pullout drawer from being collapsed with the Escape key."] = "禁用ESC鍵關閉寵物/組合列表."
	L["Stay for pet battle"] = "寵物對戰時顯示 Rematch 窗口"
	L["When a pet battle begins, keep Rematch on screen instead of hiding it. Note: the window will still close on player combat."] = "寵物對戰時顯示 Rematch 窗口.\n玩家進入戰鬥則會自動關閉 Rematch 窗口."
	L["Loading Options"] = "加載 選項"
	L["One-click loading"] = "單擊加載組合"
	L["When clicking a team in the Teams tab, instead of locking the team card, load the team immediately. If this is unchecked you can double-click a team to load it."] = "單擊加載組合."
	L["Empty missing pet slots"] = "自動清空欄位"
	L["When a team with missing pets loads and a pet is missing, empty the slot the pet would go to instead of ignoring the slot."] = "當加載的組合有戰寵無法正常加載或丟失時,自動清空該欄位."
	L["Keep companion"] = "鎖定小伙伴"
	L["After a team is loaded, summon back the companion that was at your side before the load."] = "鎖定你召喚的小伙伴,不受換寵影響."
	L["Show on injured"] = "顯示負傷戰寵"
	L["When pets load, show the window if any pets are injured. The window will show if any pets are dead or missing regardless of this setting."] = "戰寵負傷時,顯示提示窗口."
	L["Leveling Queue Options"] = "升級隊列 選項"
	L["Keep current pet on new sort"] = "鎖定當前升級寵"
	L["Do not change the current leveling pet to the top-most pet when choosing a sort order."] = "排序方式改變時,保持當前升級寵在升級欄位不變."
	L["Keep sort when emptied"] = "清空隊列時保持排序方式"
	L["When the queue is emptied, preserve the sort order and auto rotate status instead of resetting them."] = "清空隊列時,保持原來的排序方式."
	L["Hide pet toast"] = "隱藏寵物點心"
	L["Don't display the popup 'toast' when a new pet is automatically loaded from the leveling queue."] = "升級寵物時,隱藏寵物點心提示."
	L["Pet Browser Options"] = "寵物瀏覽頁選項"
	L["Use type bar"] = "啟用戰寵類型欄"
	L["Show the tabbed bar near the top of the pet browser to filter pet types, pets that are strong or tough vs chosen types."] = "啟用戰寵類型篩選欄."
	L["Only battle pets"] = "只顯示戰寵"
	L["Never list pets that can't battle in the pet browser, such as Guild Heralds. Note: most filters like rarity, level or stats will not include non-battle pets already."] = "只顯示戰鬥寵物,隱藏非戰鬥寵物."
	L["Disable sharing"] = "禁用分享"
	L["Disable the Send button and also block any incoming pets sent by others. Import and Export still work."] = "禁用發送按鈕,但不影響導入和導出功能."
	L["Use Battle.net (beta)"] = "啟用Battle.net好友分享"
	L["If both you and the recipient have this option checked, teams can be sent to or from battle.net friends. Note: The recipient needs Rematch 3.0 or greater."] = "發送組合給Battle.net好友.\n只支持Rematch_3.0以上版本."
	L["Hide tooltips"] = "隱藏提示"
	L["Hide the more common tooltips within Rematch."] = "隱藏常用功能的鼠標提示."
	L["Even alerts"] = "隱藏警告提示"
	L["Also hide tooltips that warn when you can't place a pet somewhere. This is not recommended if you're new to the addon."] = "隱藏警告提示.\n如果你對本插件不熟悉,不建議啟用該選項."
	L["Use minimap button"] = "小地圖按鈕"
	L["Place a button on the minimap to toggle Rematch."] = "啟用 Rematch 小地圖按鈕."
	L["Hide journal button"] = "隱藏寵物日誌的 Rematch 按鈕"
	L["Do not place a Rematch button along the bottom of the default Pet Journal."] = "隱藏默認寵物日誌底部的 Rematch 按鈕."
	L["Go to the key binding window to create or change bindings for Rematch."] = "在按鍵設置介面設定/更改 Rematch 的快捷鍵."
	L["Import Pet Battle Teams"] = "從 Pet Battle Teams 導入"
	L["Copy the teams from the addon Pet Battle Teams to the current team tab in Rematch."] = "將 Pet Battle Teams 的組合導入到當前組合標籤中."
	L["Toggle Rematch"] = "切換 Rematch"
	L["\124cffffd200%s\124r copied."] = "\124cffffd200%s\124r 已複製."
	L["\124cffffd200%s\124r not copied. A team of that name already exists."] = "\124cffffd200%s\124r 未復制,該組合名已存在."
	L["Pet Battle Teams Imported"] = "寵物組合已導入"
	L["Copy again and overwrite?"] = "再次複製並覆蓋?"
	L["%d teams copied successfully."] = "%d 組合複製完成."
	L["\n\n%d teams were not copied because teams already exist in Rematch with the same names."] = "\n\n%d 組合未復制,組合名已存在."
	L["Pets Tab Closed"] = "寵物標籤關閉"
	L["The pet journal's search box can't be used while the pet tab is open, sorry!"] = "當寵物瀏覽頁面開啟時,默認寵物日誌搜索欄無法使用!"

-- petloading.lua
	L["Loading..."] = "加載中..."

-- roster.lua
	L["Battle"] = "尋找對戰"
	L["Quantity"] = "數量"
	L["Favorite"] = "最喜愛的"
	L["Zone"] = "區域"
	L["Filters: \124cffffffff"] = "過濾器:\124cffffffff"
	L["Search, "] = "搜索, "
	L["Type, "] = "類型, "
	L["Strong, "] = "克制, "
	L["Tough, "] = "減傷, "
	L["Sources, "] = "來源, "
	L["Rarity, "] = "稀有, "
	L["Collected, "] = "已收集, "

-- save.lua
	L["Save As..."] = "保存為..."
	L["Save this team?"] = "保存這個組合?"
	L["New Team"] = "新建組合"
	L["A team already has this name."] = "組合名已存在！"
	L["Overwrite this team?"] = "覆蓋這個組合?"
	L["Import Team"] = "導入組合"
	L["A team already has this name.\nClick \124TInterface\\RaidFrame\\ReadyCheck-Ready:16\124t to choose a name."] = "組合名已存在！\n點擊 \124TInterface\\RaidFrame\\ReadyCheck-Ready:16\124t 重設名稱."
	L["Import As..."] = "導入為..."
	L["Send this team?"] = "發送這個組合?"
	L["Who would you like to send this team to?"] = "輸入對方暱稱即可發送該戰寵組合."
	L["Team received!"] = "對方已經收到！"
	L["Sending..."] = "發送中..."
	L["No response. Lag or no Rematch?"] = "對方無響應.（延遲高或對方沒有安裝Rematch）"
	L["They do not appear to be online."] = "對方不在線.（請檢查輸入的暱稱是否正確）"
	L["They're busy. Try again later."] = "對方繁忙. 請稍後重試."
	L["They're in combat. Try again later."] = "對方戰鬥中. 請稍後重試."
	L["They have team sharing disabled."] = "對方關閉了組合分享功能."
	L["Incoming Rematch Team"] = "收到戰寵組合"
	L["\124cffffd200%s\124r has sent you a team named \124cffffd200\"%s\"\124r"] = "\124cffffd200%s\124r 給你發送了一個組合: \124cffffd200\"%s\"\124r"

-- teams.lua
	L["New Tab"] = "新建標籤"
	L["Create a new tab."] = "創建一個新標籤."
	L["Choose a name and icon."] = "選擇名稱和圖標."
	L["Delete this tab?"] = "刪除該標籤?"
	L["Teams in this tab will be moved to the General tab."] = "該標籤中的組合將移至綜合標籤中."
	L["Load this team?"] = "加載該組合?"
	L["Rename this team?"] = "重命名該組合?"

-- browser.lua
	L["Strong vs"] = "克制"
	L["Tough vs"] = "減傷"
	L["Pets:"] = "寵物總數:"
	L["Owned:"] = "已收集:"

end
