
--[[
輕描半面妝 米奈希爾 TW伺服器 2014-2-20 早期翻譯
 2014.11.8 kptit _ 重庆铜梁 for v3.1.8  (补充补分简体汉化)
]]

local _,L = ...
if GetLocale()=="zhCN" then
--附加的
L["Rematch"] = "宠物组合"
L["Rematch version "] = "Rematch版本："

-- 3.1.8:
L["Without Any 25s"] = "未满25级"

-- 3.1.4:
L["Only Level 25s"] = "仅25级的"
L["Level 25"] = "25级"
L["Reset filters on login"] = "登陆时复位过滤器设定"
L["Reset all pet browser filters (except sort order) when logging in."] = "将重置过滤器的所有设定(宠物技能设置除外)。"
L["Load Filters"] = "读取过滤器设定"
L["Save Filters"] = "保存过滤器设定"
L["Do you want to overwrite the existing saved filters?"] = "准备更新过滤器设定？"

-- 3.1.3:
L["This team did not automatically load because you've already auto-loaded a team from where you're standing."] = "该组合没有被加载，因为刚刚已经自动加载了另一个组合。"
L["This pet is currently slotted."] = "这只宠物已在宠物槽内"

-- 3.1.2:
L["Undo"] = "撤消"
L["Revert to the last saved notes. Changes are saved when leaving these notes."] = "恢复上次保存的记录。"
L["Delete Notes"] = "删除记录"
L["Escape Key Behavior"] = "返回选项"
L["Disable ESC for notes"] = "禁用Esc键关闭记录"
L["Prevent the notes card from being dismissed with the Escape key."] = "防止记录卡被Esc键关闭造成误操作。"
L["Close everything with ESC"] = "Esc关闭"
L["Close all Escape-enabled Rematch windows at once with the Escape key instead of one at a time."] = "用Esc关闭所有窗口。"

-- 3.1.1:
L["Show notes in battle"] = "对战中显示注释"
L["If the loaded team has notes, display and lock the notes when you enter a pet battle."] = "对战中显示并锁定宠物注释。"
L["Hide rarity borders"] = "隐藏边框着色"
L["Hide the colored borders to indicate rarity around current pets and pets on the team cards."] = "隐藏稀有宠物图标的边框着色。"
L["Discard loaded team on changes"] = "忽略宠物战队变化"
L["This option changes the normal behavior of Rematch and its interaction with targets. Specifically, any time you change pets or abilities, it will disregard what you have loaded in the past and always offer to load/show teams. Also, it will be very difficult to save changes to teams by targeting. The Reload button will also be disabled. \124cffff2222WARNING!\124cffffd200 This option is not recommended!"] = "忽略战队里：宠物/技能的变化，直接按目标加载，重载按钮将无法使用。\124cffff2222注意！\124cffffd200 不建议开启！"

-- 3.1.0:
L["List real names"] = "宠物原始名称"
L["Even if a pet has been renamed, list each pet by its real name."] = "在宠物列表里显示宠物原本的名字。"
L["Fill the leveling queue with one of each species that can level from the filtered pet browser, and for which you don't have a level 25 already."] = "当升级列表里没有升级宠物时，自动添加可以升级的宠物进入升级列表进行升级。"
L["Fill Queue More"] = "批量加入升级队列"
L["Fill the leveling queue with one of each species that can level from the filtered pet browser, regardless whether you have any at level 25 already."] = "从浏览器当中选择可以升级的宠物，批量添加进升级队列。"
L["\124cffccccccThere are no notes for this team.\n\nYou can add a note by right-clicking the team in the team tab and choosing Set Notes."] = "\124cffcccccc这个组合还没有注释.\n\n右键选择该组合以添加注释"
L["Notes for this team:"] = "注释："
L["Set Notes"] = "添加注释"
L["Save these notes?"] = "保存注释？"

-- 3.0.13:
L["Reload"] = "刷新"
L[" \124cffffd200Note:\124r Enabling this option disables the 'Reload' button."] = " \124cffffd200注意:\124r 啟用此選項將禁用‘刷新’按鍵."

--3.0.11:
L["Even options"] = "隐藏提示"
L["Also hide tooltips that appear here in the options panel. This is not recommended if you're new to the addon."] = "隐藏选项菜单中的各项提示。"
L["Larger list text"] = "小字体显示"
L["Make the text in the scrollable lists (pets, teams and options) a little bigger."] = "使选项菜单文字变小，并可以滚动显示长的段落。"
L["Reverse dialog direction"] = "侧边反向"
L["This setting controls which side of the Rematch window popup dialogs will appear.\n\nRegardless of this setting, when the window is expanded, unless the 'Show dialogs at side' option is checked, they will appear in the middle of the window.\n\n\Otherwise:\n\n\124cffffd200When this option is disabled:\124r Dialogs will appear in the direction that the pullout drawer grows.\n\n\124cffffd200When this option is enabled:\124r Dialogs will appear in the opposite direction that the pullout drawer grows."] = "现在选项和各种提示将出现在窗口另一侧。"
--L["When displaying a popup dialog adjacent to the Rematch window, make them appear on the side towards the edge of the screen instead of towards the center."] = "现在选项和各种提示将出现在窗口另一侧。"
L["In a Team"] = "在一个组合里"
L["Not In a Team"] = "未在一个组合里"

--3.0.10
L["Stay after loading"] = "窗口保持"
L["Keep the Rematch window on screen after loading a team when the window was shown via 'Auto show on target'."] = "当显示后，将一直保持插件窗口。"
L["Show after loading"] = "加载后显示"
L["When a team is automatically loaded, show the Rematch window if it's not already shown."] = "当一个组合自动加载时，显示插件窗口。"

--3.0.9
L["Show dialogs at side"] = "选项菜单侧边显示"
L["Instead of making popup dialogs appear in the middle of the expanded Rematch window, make them appear to the side."] = "选项菜单将在侧边显示，不会再遮盖窗口了。"

-- browser.lua
L["Strong vs"] = "克制"
L["Tough vs"] = "少承受"
L["Your pets:"] = "你的小宠物："
L["Owned: \124cffffffff%d\124r\nMissing: \124cffffffff%d\124r\nUnique: \124cffffffff%d\124r\nLevel 25: \124cffffffff%d"] = "拥有: \124cffffffff%d\124r\n未有: \124cffffffff%d\124r\n独特: \124cffffffff%d\124r\n25级: \124cffffffff%d"
L["Pets:"] = "宠物:"
L["Owned:"] = "拥有:"

--common.lua
L["Toggle Window"] = "窗口操作"
L["Toggle Auto Load"] = "自动加载组合"
L["Toggle Pets"] = "切换宠物"
L["Toggle Teams"] = "切换组合"
L["Toggles the Rematch window to manage battle pets and teams."] = "打开宠物组合设定窗口。"

--current.lua
L["Current Battle Pets"] = "当前战宠"

--floatingpetcard.lua
L["Damage Taken"] = "伤害"
L["from"] = "承受"
L["abilities"] = "伤害"
L["No breeds known :("] = "没有发现:("
L["\124cffddddddPossible level 25 \124cff0070ddRares"] = "\124cffdddddd可能是25级 \124cff0070dd稀有宠物。"

--leveling.lua
L["Leveling:"] = "经验BB"
L["Sort:"] = "排序"
L["This is the leveling slot.\n\nDrag a level 1-24 pet here to set it as the current leveling pet.\n\nWhen a team is saved with the current leveling pet, that pet's place on the team is reserved for future leveling pets.\n\nThis slot can contain as many leveling pets as you want. When a pet reaches 25 the topmost pet in the queue becomes your new leveling pet."] = "这是升级宠物"
L["\124TInterface\\Buttons\\UI-GroupLoot-Pass-Up:16\124t This pet can't level"] = "\124TInterface\\Buttons\\UI-GroupLoot-Pass-Up:16\124t 宠物等级不在升级范围内。"
L["\124TInterface\\Buttons\\UI-GroupLoot-Pass-Up:16\124t The queue is sorted"] = "\124TInterface\\Buttons\\UI-GroupLoot-Pass-Up:16\124t 升级列表排序"
L["This pet is already in the queue.\nPets can't move while the\nqueue is sorted"] = "这只宠物已经在队列里了\n不能移动\n对其重新排序"
L["\124TInterface\\DialogFrame\\UI-Dialog-Icon-AlertNew:16\124t The queue is sorted"] = "\124TInterface\\DialogFrame\\UI-Dialog-Icon-AlertNew:16\124t 升级列表排序"
L["This pet will be added to the\nend of the unsorted queue."] = "这只宠物将被移至队列前端"
L["\124cffff8800The current leveling pet is in battle and can't be swapped."] = "\124cffff8800战斗中不能交换。"
L["Next leveling pet:"] = "下一只升级宠："
L["Queued:"] = "队列:"

--main.lua
L["Import"] = "导入"
L["Options"] = "选项"
L["\124cffff8800You're in combat. Blizzard has restrictions on what we can do with pets during combat. Try again when you're out of combat. Sorry!"] = "\124cffff8800 Rematch插件提示：暴雪禁止在战斗中打开宠物面板。"
L["\124cffffff00Rematch Auto Load is now"] = "\124cffffff00Rematch自动加载-"
L["\124cff00ff00Enabled"] = "\124cff00ff00已启动！"
L["\124cffff0000Disabled"] = "\124cffff0000已禁用！"
L["Current Battle Pets"] = "当前宠物"
L["\124cffffd200PetBattleTeams is not enabled. Try again when the addon is enabled."] = "\124cffffd200宠物组合未启用，请开启插件再试一次。"
L["Teams"] = "组合"

--options.lua
L["Targeting Options"] = "目标选项"
L["Auto show on target"] = "自动显示"
L["When targeting something with a saved team not already loaded, show the Rematch window."] = "当目标有宠物组合，但尚未加载时显示插件窗口。"
L["Window Options"] = "窗口选项"
L["Larger window"] = "放大窗口"
L["Make the Rematch window larger for easier viewing."] = "大窗口更加有利于观看。"
L["Reverse pullout"] = "菜单栏顶置"
L["When the Pets or Teams tab is opened, expand the window down the screen instead of up."] = "菜单栏将显示在搜索条上面。"
L["Lock window position"] = "锁定窗口位置"
L["Prevent the Rematch window from being dragged unless Shift is held."] = "避免误将窗口位置移动。"
L["Lock window height"] = "锁定窗口高度"
L["Prevent the window's height from being resized with the resize grip along the bottom of the expanded window."] = "防止窗口高度在底部拉动操作中变动。"
L["Disable ESC for window"] = "禁用Esc键关闭窗口"
L["Prevent the Rematch window from being dismissed with the Escape key."] = "避免误操作将总窗口关闭。"
L["Disable ESC for drawer"] = "禁用Esc键关闭拉动"
L["Prevent the pullout drawer from being collapsed with the Escape key."] = "避免误操作将拉动操作关闭。"
L["Stay for pet battle"] = "对战时窗口保持"
L["When a pet battle begins, keep Rematch on screen instead of hiding it. Note: the window will still close on player combat."] = "宠物对战时窗口将一直显示。注：玩家进入战斗时窗口将隐藏。"
L["Stay while targeting"] = "目标时窗口保持"
L["Do not dismiss the Rematch window with ESC until there is no target."] = "选中目标时将一直显示窗口，除非按Esc键关闭。"
L["Loading Options"] = "加载选项"
L["One-click loading"] = "单击加载"
L["When clicking a team in the Teams tab, instead of locking the team card, load the team immediately. If this is unchecked you can double-click a team to load it."] = "当点击一个组合名称时将进行加载，如不成功也可进行双击强行加载。"
L["Empty missing pet slots"] = "宠物栏自动清空"
L["When a team with missing pets loads and a pet is missing, empty the slot the pet would go to instead of ignoring the slot."] = "当加载一个组合时有宠物丢失，则该宠物栏将自动清空。"
L["Keep companion"] = "锁定召唤的宠物"
L["After a team is loaded, summon back the companion that was at your side before the load."] = "保持你召唤的小宠物不变动。"
L["Show on injured"] = "残血提示"
L["When pets load, show the window if any pets are injured. The window will show if any pets are dead or missing regardless of this setting."] = "当加载组合有宠物生命值不满残血时，显示提示窗口。"
L["Leveling Queue Options"] = "升级列表选项"
L["Keep current pet on new sort"] = "锁定当前升级宠物"
L["Do not change the current leveling pet to the top-most pet when choosing a sort order."] = "升级队列排序改变时，保持当前升级宠物在升级栏不变动。"
L["Keep sort when emptied"] = "保持排序方式"
L["When the queue is emptied, preserve the sort order and auto rotate status instead of resetting them."] = "当升级队列完成时，将保持原来的队列排序设置，不会重置。"
L["Hide pet toast"] = "隐藏宠物糕点"
L["Don't display the popup 'toast' when a new pet is automatically loaded from the leveling queue."] = "当加载新组合时，不再弹出糕点提示。"
L["Pet Browser Options"] = "宠物浏览器选项"
L["Use type bar"] = "类型条"
L["Show the tabbed bar near the top of the pet browser to filter pet types, pets that are strong or tough vs chosen types."] = "在浏览器顶部显示类型图标栏。"
L["Only battle pets"] = "只显示可以对战的宠物"
L["Never list pets that can't battle in the pet browser, such as Guild Heralds. Note: most filters like rarity, level or stats will not include non-battle pets already."] = "没有列出的宠物，均不能进行对战。注：浏览器统计是不包括非战斗宠物的。"
L["Disable sharing"] = "关闭组合分享"
L["Disable the Send button and also block any incoming pets sent by others. Import and Export still work."] = "禁用组合发送按键，不会影响导入和导出功能。"
L["Use Battle.net (beta)"] = "战网实名好友分享(测试)"
L["If both you and the recipient have this option checked, teams can be sent to or from battle.net friends. Note: The recipient needs Rematch 3.0 or greater."] = "可以发送组合给实名好友了。注：需要3.0及以上版本。"
L["Hide tooltips"] = "隐藏提示"
L["Hide the more common tooltips within Rematch."] = "隐藏常用功能的鼠标提示。"
L["Even alerts"] = "隐藏警告提示"
L["Also hide tooltips that warn when you can't place a pet somewhere. This is not recommended if you're new to the addon."] = "将隐藏不能进行对战等警告提示，\n如果你不熟悉本插件，不建议开启。"
L["Use minimap button"] = "小地图按钮"
L["Place a button on the minimap to toggle Rematch."] = "在迷你小地图上显示Rematch小图标。"
L["Hide journal button"] = "隐藏Rematch按键"
L["Do not place a Rematch button along the bottom of the default Pet Journal."] = "在系统宠物面板底部不再显示Rematch按键。"
L["Go to the key binding window to create or change bindings for Rematch."] = "快捷键设定"
L["Import Pet Battle Teams"] = "导入组合信息"
L["Copy the teams from the addon Pet Battle Teams to the current team tab in Rematch."] = "复制该组合信息，可以分享给其他人该配队组合。"
L["Toggle Rematch"] = "关启或关闭"
L["Options"] = "选项"
L["\124cffffd200%s\124r copied."] = "\124cffffd200%s\124r复制。"
L["\124cffffd200%s\124r not copied. A team of that name already exists."] = "\124cffffd200%s\124r不能复制，该组合名称已经存在了。"
L["Pet Battle Teams Imported"] = "宠物组合导入"
L["Copy again and overwrite?"] = "需要覆盖原有组合吗？"
L["%d teams copied successfully."] = "%d个组合成功复制。"
L["\n\n%d teams were not copied because teams already exist in Rematch with the same names."] = "\n\n%d个组合没有复制成功，因为有相同名称组合存在。"
L["Pets Tab Closed"] = "关闭系统宠物面板"
L["The pet journal's search box can't be used while the pet tab is open, sorry!"] = "当插件浏览器打开时，不能打开系统宠物面板。"
L["Start Leveling"] = "开始升级"
L["Add to Leveling Queue"] = "添加进升级列表"
L["Stop Leveling"] = "移出升级列表"
--3.0.4加入
L["Auto load"] = "自动加载"
L["When your mouseover or target has a saved team not already loaded, load the team immediately."] = "当鼠标悬停或指定目标时，针对该目标的组合即自动加载。"
L["On target only"] = "仅选定目标时加载"
L["Auto load will only happen when you target, not mouseover. \124cffff2222WARNING!\124cffffd200 This option is not recommended! It is often too late to load pets when a battle starts if you target with right-click!"] = "当选定目标时才加载组合。"
L["Always show or load"] = "总是加载"
L["Continue to offer to load (or auto load) teams if any pets or abilities are changed in the loaded team."] = "组合里如果有宠物变动,将不会影响自动加载。"
L["Jump to key"] = "快捷跳转"
L["While the mouse is over the team list or pet browser, hitting a key will jump to the next team or pet that begins with that letter."] = "当鼠标在浏览器/升级列表上时，按字母键将跳到该字母开头的宠物BB/组合。（不支持汉字）"
--3.0.7加入
L["Don't warn about missing pets"] = "不再提示宠物丢失"
L["Don't display a popup when a team loads and a pet within the team can't be found."] = "当加载组合时，有宠物丢失不再弹出提示框。"

--petloading.lua
L["Loading..."] = "读取中..."
--3.0.7加入
L["Pets are missing!"] = "宠物丢失！"

--rmf.lua
L["Empty Slot"] = "空升级槽"
L["Choose a name."] = "选择一个名字"
L["Restore original name"] = "恢复原来名字"
L["Release this pet?"] = "释放这只宠物？"
L["Once released, this pet is gone forever!"] = "一旦释放，就没有了！"
L["Cage this pet?"] = "装入宠物笼？"
L["Current Zone"] = "最近的区域"
L["Reset All"] = "重置分类"
L["Use Type Bar"] = "目录条"
L["Strong Vs"] = "对某系克制"
L["Tough Vs"] = "少承受某系伤害"
L["Leveling"] = "升级"
L["Not Leveling"] = "未升级宠"
L["Tradable"] = "可交易"
L["Not Tradable"] = "不可交易"
L["Can Battle"] = "可对战"
L["Can't Battle"] = "不能对战"
L["1 Pet"] = "已收集1/3"
L["2+ Pets"] = "已收集2/3"
L["3+ Pets"] = "已收集3/3"
L["Put Leveling Pet Here"] = "设为升级栏"
L["Empty Slot"] = "空槽"
L["Move to Top"] = "移至顶部"
L["Move Up"] = "上移"
L["Move Down"] = "下移"
L["Move to End"] = "移到末尾"
L["Start Leveling"] = "开始升级"
L["Stop Leveling"] = "移出升级列表"
L["Fill Queue"] = "加入升级列表"
L["This will add %d pets to the leveling queue.\n%s\nAre you sure you want to fill the leveling queue?"] = "将未满级的%d个宠物加入升级列表。\n%s\n\n你确认要这么做?"
L["\nYou can reduce the number of pets by filtering them in Rematch's pet browser\n\nFor instance: search for \"21-24\" and filter Rare only to fill the queue with rares between level 21 and 24.\n"] = "\n可在X件浏览器中按条件设定加载宠物\n比如按类型\n再比如按等级\"21-24\""
L["\nAll species with a pet that can level already have a pet in the queue.\n"] = "\n在升级列表中已有相同的宠物了。\n"
L["Empty Queue"] = "清空升级列表"
L["Are you sure you want to remove all pets from the leveling queue?"] = "清空当前升级列表中所有的升级宠物？"
L["Queue"] = "列表"
L["Sort Order:"] = "排序"
L["Ascending"] = "升序"
L["Sort:\124cffffd200Ascending"] = "排序:\124cffffd200升序"
L["Sort the queue from\nlevel 1 to level 25."] = "按1~24排序"
L["Descending"] = "降序"
L["Sort:\124cffffd200Descending"] = "排序:\124cffffd200降序"
L["Sort the queue from\nlevel 25 to level 1."] = "按24~1排序"
L["Median"] = "中值"
L["Sort:\124cffffd200Median"] = "排序:\124cffffd200中值"
L["Sort the queue for\nlevels closest to 10.5."] = "按最接近10级排序"
L["Auto Rotate"] = "自动循环"
L["After the leveling pet gains xp:\n\n\124cffffd200Ascending\124cffe6e6e6 and \124cffffd200Median\124cffe6e6e6 sorts will swap\nto the top-most pet in the queue.\n\n\124cffffd200Unsorted\124cffe6e6e6 and \124cffffd200Descending\124cffe6e6e6 sort will\nswap to the next pet in the queue."] = "调整宠物队列:\n\n\124cffffd200升序\124cffe6e6e6和\124cffffd200中值等级\124cffe6e6e6将移到升级队列的最\n前端优先升级。\n\n\124cffffd200未排序\124cffe6e6e6和\124cffffd200降序\124cffe6e6e6排列下，将降至队列第\n二位置。"
L["Fill Queue"] = "添加宠物"
L["Fill the leveling queue with one of\neach species that can level from\nthe filtered pet browser."] = "\n可在X件浏览器中过滤宠物\n比如按类型\n再比如按等级\"21-24\""
L["Remove all leveling pets\nfrom the queue."] = "清空升级列表中的所有升级宠物。"
L["Edit"] = "修改"
L["Move Up"] = "上移"
L["Move Down"] = "下移"
L["Delete this team?"] = "要删除这个组合？"
L["Load"] = "加载"
L["Load Team"] = "加载组合"
L["You can double-click\na team to load also."] = "你可以双击强行加载该组合。"
L["Rename"] = "重命名"
L["Move To"] = "移至"
L["Send"] = "发送"
L["Export"] = "导出"
L["Save To"] = "保存到"

--roster.lua
L["Tradable"] = "可交易"
L["Leveling"] = "升级宠"
L["Battle"] = "可对战宠"
L["Quantity"] = "数量"
L["Favorite"] = "心爱"
L["Zone"] = "区域"
L["Filters: \124cffffffff"] = "过滤器: \124cffffffff"
L["Search, "] = "搜索, "
L["Type, "] = "类型, "
L["Strong, "] = "克制, "
L["Tough, "] = "少承受, "
L["Sources, "] = "来源, "
L["Rarity, "] = "稀有, "
L["Collected, "] = "已收集, "
L["Filters: \124cffffffff"] = "过滤器: \124cffffffff"

--save.lua
L["Save As..."] = "另存为"
L["Save this team?"] = "保存这个组合？"
L["New Team"] = "新组合"
L["A team already has this name."] = "组合重名了。"
L["Overwrite this team?"] = "覆盖原有组合吗？"
L["Import Team"] = "导入组合"
L["A team already has this name.\nClick \124TInterface\\RaidFrame\\ReadyCheck-Ready:16\124t to choose a name."] = "重名了！\n点击 \124TInterface\\RaidFrame\\ReadyCheck-Ready:16\124t 设定名称。"
L["Import As..."] = "导入中..."
L["Send this team?"] = "发送该组合？"
L["Who would you like to send this team to?"] = "谁要该组合？"
L["Team received!"] = "对方已经收到该组合了！"
L["Sending..."] = "发送中..."
L["No response. Lag or no Rematch?"] = "对方无响应，延迟高或对方没有安装Rematch！"
L["They do not appear to be online."] = "对方不在线！（请检查输入的姓名是否正确）"
L["They're busy. Try again later."] = "对方有另一个组合在等待\n请稍后再试！"
L["They're in combat. Try again later."] = "对方在战斗中，请稍后再试！"
L["They have team sharing disabled."] = "对方关闭了组合分享功能！"
L["Incoming Rematch Team"] = "接收组合"
L["\124cffffd200%s\124r has sent you a team named \124cffffd200\"%s\"\124r"] = "\124cffffd200%s\124r 给你发送了一个宠物对战组合 \124cffffd200\"%s\"\124r"
L["A team already has this name.\nClick \124TInterface\\RaidFrame\\ReadyCheck-Ready:16\124t to choose a name."] = "重名了！\n点击 \124TInterface\\RaidFrame\\ReadyCheck-Ready:16\124t 设定名称。"
L["Press CTRL+V to paste a team from the clipboard."] = "宠物组合代码，Ctrl+V复制导入。"
L["Press CTRL+C to copy this team to the clipboard."] = "下方是该组合的代码，Ctrl+C复制即可分享。"

--teams.lua
L["New Tab"] = "新标签"
L["Create a new tab."] = "创建一个新的标签卡"
L["Choose a name and icon."] = "选择一个名称和图标"
L["Delete this tab?"] = "要删除这个组合？"
L["Teams in this tab will be moved to the General tab."] = "这个标签中的组合将移至综合标签卡项目中。"
L["Load this team?"] = "加载该组合？"
L["Rename this team?"] = "重命名该组合？"
end;
